// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waves_adapter.proto

package blockchain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message for getting last block
type BlockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{0}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

// The response message containing last block number
type BlockReply struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockReply) Reset()         { *m = BlockReply{} }
func (m *BlockReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply) ProtoMessage()    {}
func (*BlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{1}
}

func (m *BlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply.Unmarshal(m, b)
}
func (m *BlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply.Marshal(b, m, deterministic)
}
func (m *BlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply.Merge(m, src)
}
func (m *BlockReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply.Size(m)
}
func (m *BlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply proto.InternalMessageInfo

func (m *BlockReply) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

// The request message for getting information by account address
type AddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressRequest) Reset()         { *m = AddressRequest{} }
func (m *AddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()    {}
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{2}
}

func (m *AddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressRequest.Unmarshal(m, b)
}
func (m *AddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressRequest.Marshal(b, m, deterministic)
}
func (m *AddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressRequest.Merge(m, src)
}
func (m *AddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddressRequest.Size(m)
}
func (m *AddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressRequest proto.InternalMessageInfo

func (m *AddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// empty request message
type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{3}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

// fee request message
type FeeRequest struct {
	SendersPublicKey     string   `protobuf:"bytes,1,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeRequest) Reset()         { *m = FeeRequest{} }
func (m *FeeRequest) String() string { return proto.CompactTextString(m) }
func (*FeeRequest) ProtoMessage()    {}
func (*FeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{4}
}

func (m *FeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeRequest.Unmarshal(m, b)
}
func (m *FeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeRequest.Marshal(b, m, deterministic)
}
func (m *FeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRequest.Merge(m, src)
}
func (m *FeeRequest) XXX_Size() int {
	return xxx_messageInfo_FeeRequest.Size(m)
}
func (m *FeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRequest proto.InternalMessageInfo

func (m *FeeRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *FeeRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// The response message containing transaction's fee
type FeeReply struct {
	Fee                  string   `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeReply) Reset()         { *m = FeeReply{} }
func (m *FeeReply) String() string { return proto.CompactTextString(m) }
func (*FeeReply) ProtoMessage()    {}
func (*FeeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{5}
}

func (m *FeeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeReply.Unmarshal(m, b)
}
func (m *FeeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeReply.Marshal(b, m, deterministic)
}
func (m *FeeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeReply.Merge(m, src)
}
func (m *FeeReply) XXX_Size() int {
	return xxx_messageInfo_FeeReply.Size(m)
}
func (m *FeeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeReply.DiscardUnknown(m)
}

var xxx_messageInfo_FeeReply proto.InternalMessageInfo

func (m *FeeReply) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

// The response message containing account's balance
type GetBalanceReply struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceReply) Reset()         { *m = GetBalanceReply{} }
func (m *GetBalanceReply) String() string { return proto.CompactTextString(m) }
func (*GetBalanceReply) ProtoMessage()    {}
func (*GetBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{6}
}

func (m *GetBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceReply.Unmarshal(m, b)
}
func (m *GetBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceReply.Marshal(b, m, deterministic)
}
func (m *GetBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceReply.Merge(m, src)
}
func (m *GetBalanceReply) XXX_Size() int {
	return xxx_messageInfo_GetBalanceReply.Size(m)
}
func (m *GetBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceReply proto.InternalMessageInfo

func (m *GetBalanceReply) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

// The response message containing account's balance with assets balances
type GetAllBalancesReply struct {
	Amount               string                              `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetBalances        []*GetAllBalancesReply_AssetBalance `protobuf:"bytes,2,rep,name=assetBalances,proto3" json:"assetBalances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetAllBalancesReply) Reset()         { *m = GetAllBalancesReply{} }
func (m *GetAllBalancesReply) String() string { return proto.CompactTextString(m) }
func (*GetAllBalancesReply) ProtoMessage()    {}
func (*GetAllBalancesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{7}
}

func (m *GetAllBalancesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalancesReply.Unmarshal(m, b)
}
func (m *GetAllBalancesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalancesReply.Marshal(b, m, deterministic)
}
func (m *GetAllBalancesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalancesReply.Merge(m, src)
}
func (m *GetAllBalancesReply) XXX_Size() int {
	return xxx_messageInfo_GetAllBalancesReply.Size(m)
}
func (m *GetAllBalancesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalancesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalancesReply proto.InternalMessageInfo

func (m *GetAllBalancesReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetAllBalancesReply) GetAssetBalances() []*GetAllBalancesReply_AssetBalance {
	if m != nil {
		return m.AssetBalances
	}
	return nil
}

type GetAllBalancesReply_AssetBalance struct {
	AssetId              string   `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBalancesReply_AssetBalance) Reset()         { *m = GetAllBalancesReply_AssetBalance{} }
func (m *GetAllBalancesReply_AssetBalance) String() string { return proto.CompactTextString(m) }
func (*GetAllBalancesReply_AssetBalance) ProtoMessage()    {}
func (*GetAllBalancesReply_AssetBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{7, 0}
}

func (m *GetAllBalancesReply_AssetBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Unmarshal(m, b)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Marshal(b, m, deterministic)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalancesReply_AssetBalance.Merge(m, src)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Size() int {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Size(m)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalancesReply_AssetBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalancesReply_AssetBalance proto.InternalMessageInfo

func (m *GetAllBalancesReply_AssetBalance) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *GetAllBalancesReply_AssetBalance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The response message containing generated address
type GenerateAddressReply struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressReply) Reset()         { *m = GenerateAddressReply{} }
func (m *GenerateAddressReply) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressReply) ProtoMessage()    {}
func (*GenerateAddressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{8}
}

func (m *GenerateAddressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressReply.Unmarshal(m, b)
}
func (m *GenerateAddressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressReply.Marshal(b, m, deterministic)
}
func (m *GenerateAddressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressReply.Merge(m, src)
}
func (m *GenerateAddressReply) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressReply.Size(m)
}
func (m *GenerateAddressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressReply proto.InternalMessageInfo

func (m *GenerateAddressReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// The response message containing result of address's validation
type ValidateAddressReply struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressReply) Reset()         { *m = ValidateAddressReply{} }
func (m *ValidateAddressReply) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressReply) ProtoMessage()    {}
func (*ValidateAddressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{9}
}

func (m *ValidateAddressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressReply.Unmarshal(m, b)
}
func (m *ValidateAddressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressReply.Marshal(b, m, deterministic)
}
func (m *ValidateAddressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressReply.Merge(m, src)
}
func (m *ValidateAddressReply) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressReply.Size(m)
}
func (m *ValidateAddressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressReply proto.InternalMessageInfo

func (m *ValidateAddressReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// The request message for raw transaction creation
type RawTransactionBySendersAddressRequest struct {
	AddressFrom          string   `protobuf:"bytes,1,opt,name=addressFrom,proto3" json:"addressFrom,omitempty"`
	AddressTo            string   `protobuf:"bytes,2,opt,name=addressTo,proto3" json:"addressTo,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionBySendersAddressRequest) Reset()         { *m = RawTransactionBySendersAddressRequest{} }
func (m *RawTransactionBySendersAddressRequest) String() string { return proto.CompactTextString(m) }
func (*RawTransactionBySendersAddressRequest) ProtoMessage()    {}
func (*RawTransactionBySendersAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{10}
}

func (m *RawTransactionBySendersAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionBySendersAddressRequest.Unmarshal(m, b)
}
func (m *RawTransactionBySendersAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionBySendersAddressRequest.Marshal(b, m, deterministic)
}
func (m *RawTransactionBySendersAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionBySendersAddressRequest.Merge(m, src)
}
func (m *RawTransactionBySendersAddressRequest) XXX_Size() int {
	return xxx_messageInfo_RawTransactionBySendersAddressRequest.Size(m)
}
func (m *RawTransactionBySendersAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionBySendersAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionBySendersAddressRequest proto.InternalMessageInfo

func (m *RawTransactionBySendersAddressRequest) GetAddressFrom() string {
	if m != nil {
		return m.AddressFrom
	}
	return ""
}

func (m *RawTransactionBySendersAddressRequest) GetAddressTo() string {
	if m != nil {
		return m.AddressTo
	}
	return ""
}

func (m *RawTransactionBySendersAddressRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The request message for raw transaction creation
type RawTransactionRequest struct {
	AddressFrom          string   `protobuf:"bytes,1,opt,name=addressFrom,proto3" json:"addressFrom,omitempty"`
	SendersPublicKey     string   `protobuf:"bytes,2,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AddressTo            string   `protobuf:"bytes,3,opt,name=addressTo,proto3" json:"addressTo,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId              string   `protobuf:"bytes,5,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionRequest) Reset()         { *m = RawTransactionRequest{} }
func (m *RawTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*RawTransactionRequest) ProtoMessage()    {}
func (*RawTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{11}
}

func (m *RawTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionRequest.Unmarshal(m, b)
}
func (m *RawTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionRequest.Marshal(b, m, deterministic)
}
func (m *RawTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionRequest.Merge(m, src)
}
func (m *RawTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_RawTransactionRequest.Size(m)
}
func (m *RawTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionRequest proto.InternalMessageInfo

func (m *RawTransactionRequest) GetAddressFrom() string {
	if m != nil {
		return m.AddressFrom
	}
	return ""
}

func (m *RawTransactionRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *RawTransactionRequest) GetAddressTo() string {
	if m != nil {
		return m.AddressTo
	}
	return ""
}

func (m *RawTransactionRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RawTransactionRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// The response message containing raw transaction
type RawTransactionReply struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionReply) Reset()         { *m = RawTransactionReply{} }
func (m *RawTransactionReply) String() string { return proto.CompactTextString(m) }
func (*RawTransactionReply) ProtoMessage()    {}
func (*RawTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{12}
}

func (m *RawTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionReply.Unmarshal(m, b)
}
func (m *RawTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionReply.Marshal(b, m, deterministic)
}
func (m *RawTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionReply.Merge(m, src)
}
func (m *RawTransactionReply) XXX_Size() int {
	return xxx_messageInfo_RawTransactionReply.Size(m)
}
func (m *RawTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionReply proto.InternalMessageInfo

func (m *RawTransactionReply) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The request message for singing transaction
type SignTransactionRequest struct {
	SenderAddress        string   `protobuf:"bytes,1,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	Tx                   []byte   `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionRequest) Reset()         { *m = SignTransactionRequest{} }
func (m *SignTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SignTransactionRequest) ProtoMessage()    {}
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{13}
}

func (m *SignTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionRequest.Unmarshal(m, b)
}
func (m *SignTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SignTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionRequest.Merge(m, src)
}
func (m *SignTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SignTransactionRequest.Size(m)
}
func (m *SignTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionRequest proto.InternalMessageInfo

func (m *SignTransactionRequest) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *SignTransactionRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The request message for singing transaction by private key in parameters
type SignTransactionBySecretKeyRequest struct {
	SenderSecretKey      string   `protobuf:"bytes,1,opt,name=senderSecretKey,proto3" json:"senderSecretKey,omitempty"`
	Tx                   []byte   `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionBySecretKeyRequest) Reset()         { *m = SignTransactionBySecretKeyRequest{} }
func (m *SignTransactionBySecretKeyRequest) String() string { return proto.CompactTextString(m) }
func (*SignTransactionBySecretKeyRequest) ProtoMessage()    {}
func (*SignTransactionBySecretKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{14}
}

func (m *SignTransactionBySecretKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionBySecretKeyRequest.Unmarshal(m, b)
}
func (m *SignTransactionBySecretKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionBySecretKeyRequest.Marshal(b, m, deterministic)
}
func (m *SignTransactionBySecretKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionBySecretKeyRequest.Merge(m, src)
}
func (m *SignTransactionBySecretKeyRequest) XXX_Size() int {
	return xxx_messageInfo_SignTransactionBySecretKeyRequest.Size(m)
}
func (m *SignTransactionBySecretKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionBySecretKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionBySecretKeyRequest proto.InternalMessageInfo

func (m *SignTransactionBySecretKeyRequest) GetSenderSecretKey() string {
	if m != nil {
		return m.SenderSecretKey
	}
	return ""
}

func (m *SignTransactionBySecretKeyRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The response message containing signed transaction
type SignTransactionReply struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	TxHash               string   `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionReply) Reset()         { *m = SignTransactionReply{} }
func (m *SignTransactionReply) String() string { return proto.CompactTextString(m) }
func (*SignTransactionReply) ProtoMessage()    {}
func (*SignTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{15}
}

func (m *SignTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionReply.Unmarshal(m, b)
}
func (m *SignTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionReply.Marshal(b, m, deterministic)
}
func (m *SignTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionReply.Merge(m, src)
}
func (m *SignTransactionReply) XXX_Size() int {
	return xxx_messageInfo_SignTransactionReply.Size(m)
}
func (m *SignTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionReply proto.InternalMessageInfo

func (m *SignTransactionReply) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SignTransactionReply) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// The request message for singing transaction
type SendTransactionRequest struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{16}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The response message containing transaction's id
type SendTransactionReply struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionReply) Reset()         { *m = SendTransactionReply{} }
func (m *SendTransactionReply) String() string { return proto.CompactTextString(m) }
func (*SendTransactionReply) ProtoMessage()    {}
func (*SendTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{17}
}

func (m *SendTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionReply.Unmarshal(m, b)
}
func (m *SendTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionReply.Marshal(b, m, deterministic)
}
func (m *SendTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionReply.Merge(m, src)
}
func (m *SendTransactionReply) XXX_Size() int {
	return xxx_messageInfo_SendTransactionReply.Size(m)
}
func (m *SendTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionReply proto.InternalMessageInfo

func (m *SendTransactionReply) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// The request message for getting transaction's status containing tx id
type GetTransactionStatusRequest struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionStatusRequest) Reset()         { *m = GetTransactionStatusRequest{} }
func (m *GetTransactionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusRequest) ProtoMessage()    {}
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{18}
}

func (m *GetTransactionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusRequest.Unmarshal(m, b)
}
func (m *GetTransactionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusRequest.Merge(m, src)
}
func (m *GetTransactionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusRequest.Size(m)
}
func (m *GetTransactionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusRequest proto.InternalMessageInfo

func (m *GetTransactionStatusRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// The response message containing transaction's status: UNKNOWN, PENDING, SUCCESS
type GetTransactionStatusReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionStatusReply) Reset()         { *m = GetTransactionStatusReply{} }
func (m *GetTransactionStatusReply) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusReply) ProtoMessage()    {}
func (*GetTransactionStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{19}
}

func (m *GetTransactionStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusReply.Unmarshal(m, b)
}
func (m *GetTransactionStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusReply.Marshal(b, m, deterministic)
}
func (m *GetTransactionStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusReply.Merge(m, src)
}
func (m *GetTransactionStatusReply) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusReply.Size(m)
}
func (m *GetTransactionStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusReply proto.InternalMessageInfo

func (m *GetTransactionStatusReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// The request message for getting transaction by hash
type TransactionByHashRequest struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionByHashRequest) Reset()         { *m = TransactionByHashRequest{} }
func (m *TransactionByHashRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionByHashRequest) ProtoMessage()    {}
func (*TransactionByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{20}
}

func (m *TransactionByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionByHashRequest.Unmarshal(m, b)
}
func (m *TransactionByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionByHashRequest.Marshal(b, m, deterministic)
}
func (m *TransactionByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionByHashRequest.Merge(m, src)
}
func (m *TransactionByHashRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionByHashRequest.Size(m)
}
func (m *TransactionByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionByHashRequest proto.InternalMessageInfo

func (m *TransactionByHashRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// The response message for getting transaction by hash
type TransactionByHashReply struct {
	SenderAddress        string         `protobuf:"bytes,1,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	SendersPublicKey     string         `protobuf:"bytes,2,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	RecipientAddress     string         `protobuf:"bytes,3,opt,name=recipientAddress,proto3" json:"recipientAddress,omitempty"`
	Amount               string         `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId              string         `protobuf:"bytes,5,opt,name=assetId,proto3" json:"assetId,omitempty"`
	TxHash               string         `protobuf:"bytes,6,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Fee                  string         `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Data                 []byte         `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Status               string         `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Inputs               []*InputOutput `protobuf:"bytes,10,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*InputOutput `protobuf:"bytes,11,rep,name=outputs,proto3" json:"outputs,omitempty"`
	AssetAmount          string         `protobuf:"bytes,12,opt,name=assetAmount,proto3" json:"assetAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionByHashReply) Reset()         { *m = TransactionByHashReply{} }
func (m *TransactionByHashReply) String() string { return proto.CompactTextString(m) }
func (*TransactionByHashReply) ProtoMessage()    {}
func (*TransactionByHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{21}
}

func (m *TransactionByHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionByHashReply.Unmarshal(m, b)
}
func (m *TransactionByHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionByHashReply.Marshal(b, m, deterministic)
}
func (m *TransactionByHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionByHashReply.Merge(m, src)
}
func (m *TransactionByHashReply) XXX_Size() int {
	return xxx_messageInfo_TransactionByHashReply.Size(m)
}
func (m *TransactionByHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionByHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionByHashReply proto.InternalMessageInfo

func (m *TransactionByHashReply) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *TransactionByHashReply) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *TransactionByHashReply) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *TransactionByHashReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionByHashReply) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *TransactionByHashReply) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TransactionByHashReply) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *TransactionByHashReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionByHashReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionByHashReply) GetInputs() []*InputOutput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TransactionByHashReply) GetOutputs() []*InputOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *TransactionByHashReply) GetAssetAmount() string {
	if m != nil {
		return m.AssetAmount
	}
	return ""
}

type InputOutput struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputOutput) Reset()         { *m = InputOutput{} }
func (m *InputOutput) String() string { return proto.CompactTextString(m) }
func (*InputOutput) ProtoMessage()    {}
func (*InputOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{22}
}

func (m *InputOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputOutput.Unmarshal(m, b)
}
func (m *InputOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputOutput.Marshal(b, m, deterministic)
}
func (m *InputOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputOutput.Merge(m, src)
}
func (m *InputOutput) XXX_Size() int {
	return xxx_messageInfo_InputOutput.Size(m)
}
func (m *InputOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_InputOutput.DiscardUnknown(m)
}

var xxx_messageInfo_InputOutput proto.InternalMessageInfo

func (m *InputOutput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InputOutput) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The request message for check address
type CheckAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAddressRequest) Reset()         { *m = CheckAddressRequest{} }
func (m *CheckAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAddressRequest) ProtoMessage()    {}
func (*CheckAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{23}
}

func (m *CheckAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAddressRequest.Unmarshal(m, b)
}
func (m *CheckAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAddressRequest.Marshal(b, m, deterministic)
}
func (m *CheckAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAddressRequest.Merge(m, src)
}
func (m *CheckAddressRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAddressRequest.Size(m)
}
func (m *CheckAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAddressRequest proto.InternalMessageInfo

func (m *CheckAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CheckAddressRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

type GetAllBalanceRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Contracts            []string `protobuf:"bytes,2,rep,name=contracts,proto3" json:"contracts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBalanceRequest) Reset()         { *m = GetAllBalanceRequest{} }
func (m *GetAllBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllBalanceRequest) ProtoMessage()    {}
func (*GetAllBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{24}
}

func (m *GetAllBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalanceRequest.Unmarshal(m, b)
}
func (m *GetAllBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetAllBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalanceRequest.Merge(m, src)
}
func (m *GetAllBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllBalanceRequest.Size(m)
}
func (m *GetAllBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalanceRequest proto.InternalMessageInfo

func (m *GetAllBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetAllBalanceRequest) GetContracts() []string {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type GetAllBalanceReply struct {
	Amount               string                             `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	TokenBalances        []*GetAllBalanceReply_TokenBalance `protobuf:"bytes,2,rep,name=tokenBalances,proto3" json:"tokenBalances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *GetAllBalanceReply) Reset()         { *m = GetAllBalanceReply{} }
func (m *GetAllBalanceReply) String() string { return proto.CompactTextString(m) }
func (*GetAllBalanceReply) ProtoMessage()    {}
func (*GetAllBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{25}
}

func (m *GetAllBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalanceReply.Unmarshal(m, b)
}
func (m *GetAllBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalanceReply.Marshal(b, m, deterministic)
}
func (m *GetAllBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalanceReply.Merge(m, src)
}
func (m *GetAllBalanceReply) XXX_Size() int {
	return xxx_messageInfo_GetAllBalanceReply.Size(m)
}
func (m *GetAllBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalanceReply proto.InternalMessageInfo

func (m *GetAllBalanceReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetAllBalanceReply) GetTokenBalances() []*GetAllBalanceReply_TokenBalance {
	if m != nil {
		return m.TokenBalances
	}
	return nil
}

type GetAllBalanceReply_TokenBalance struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBalanceReply_TokenBalance) Reset()         { *m = GetAllBalanceReply_TokenBalance{} }
func (m *GetAllBalanceReply_TokenBalance) String() string { return proto.CompactTextString(m) }
func (*GetAllBalanceReply_TokenBalance) ProtoMessage()    {}
func (*GetAllBalanceReply_TokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{25, 0}
}

func (m *GetAllBalanceReply_TokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalanceReply_TokenBalance.Unmarshal(m, b)
}
func (m *GetAllBalanceReply_TokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalanceReply_TokenBalance.Marshal(b, m, deterministic)
}
func (m *GetAllBalanceReply_TokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalanceReply_TokenBalance.Merge(m, src)
}
func (m *GetAllBalanceReply_TokenBalance) XXX_Size() int {
	return xxx_messageInfo_GetAllBalanceReply_TokenBalance.Size(m)
}
func (m *GetAllBalanceReply_TokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalanceReply_TokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalanceReply_TokenBalance proto.InternalMessageInfo

func (m *GetAllBalanceReply_TokenBalance) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GetAllBalanceReply_TokenBalance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type GetUnspentInputsReply struct {
	Utxo                 []*UnspentInput `protobuf:"bytes,1,rep,name=utxo,proto3" json:"utxo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUnspentInputsReply) Reset()         { *m = GetUnspentInputsReply{} }
func (m *GetUnspentInputsReply) String() string { return proto.CompactTextString(m) }
func (*GetUnspentInputsReply) ProtoMessage()    {}
func (*GetUnspentInputsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{26}
}

func (m *GetUnspentInputsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnspentInputsReply.Unmarshal(m, b)
}
func (m *GetUnspentInputsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnspentInputsReply.Marshal(b, m, deterministic)
}
func (m *GetUnspentInputsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnspentInputsReply.Merge(m, src)
}
func (m *GetUnspentInputsReply) XXX_Size() int {
	return xxx_messageInfo_GetUnspentInputsReply.Size(m)
}
func (m *GetUnspentInputsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnspentInputsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnspentInputsReply proto.InternalMessageInfo

func (m *GetUnspentInputsReply) GetUtxo() []*UnspentInput {
	if m != nil {
		return m.Utxo
	}
	return nil
}

type UnspentInput struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=TxId,proto3" json:"TxId,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Vout                 uint32   `protobuf:"varint,3,opt,name=Vout,proto3" json:"Vout,omitempty"`
	ScriptPubKey         string   `protobuf:"bytes,4,opt,name=ScriptPubKey,proto3" json:"ScriptPubKey,omitempty"`
	Amount               float32  `protobuf:"fixed32,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Satoshis             uint32   `protobuf:"varint,6,opt,name=Satoshis,proto3" json:"Satoshis,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=Height,proto3" json:"Height,omitempty"`
	Confirmations        uint32   `protobuf:"varint,8,opt,name=Confirmations,proto3" json:"Confirmations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnspentInput) Reset()         { *m = UnspentInput{} }
func (m *UnspentInput) String() string { return proto.CompactTextString(m) }
func (*UnspentInput) ProtoMessage()    {}
func (*UnspentInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{27}
}

func (m *UnspentInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnspentInput.Unmarshal(m, b)
}
func (m *UnspentInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnspentInput.Marshal(b, m, deterministic)
}
func (m *UnspentInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnspentInput.Merge(m, src)
}
func (m *UnspentInput) XXX_Size() int {
	return xxx_messageInfo_UnspentInput.Size(m)
}
func (m *UnspentInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnspentInput.DiscardUnknown(m)
}

var xxx_messageInfo_UnspentInput proto.InternalMessageInfo

func (m *UnspentInput) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *UnspentInput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UnspentInput) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *UnspentInput) GetScriptPubKey() string {
	if m != nil {
		return m.ScriptPubKey
	}
	return ""
}

func (m *UnspentInput) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UnspentInput) GetSatoshis() uint32 {
	if m != nil {
		return m.Satoshis
	}
	return 0
}

func (m *UnspentInput) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UnspentInput) GetConfirmations() uint32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockRequest)(nil), "blockchain.BlockRequest")
	proto.RegisterType((*BlockReply)(nil), "blockchain.BlockReply")
	proto.RegisterType((*AddressRequest)(nil), "blockchain.AddressRequest")
	proto.RegisterType((*EmptyRequest)(nil), "blockchain.EmptyRequest")
	proto.RegisterType((*FeeRequest)(nil), "blockchain.FeeRequest")
	proto.RegisterType((*FeeReply)(nil), "blockchain.FeeReply")
	proto.RegisterType((*GetBalanceReply)(nil), "blockchain.GetBalanceReply")
	proto.RegisterType((*GetAllBalancesReply)(nil), "blockchain.GetAllBalancesReply")
	proto.RegisterType((*GetAllBalancesReply_AssetBalance)(nil), "blockchain.GetAllBalancesReply.AssetBalance")
	proto.RegisterType((*GenerateAddressReply)(nil), "blockchain.GenerateAddressReply")
	proto.RegisterType((*ValidateAddressReply)(nil), "blockchain.ValidateAddressReply")
	proto.RegisterType((*RawTransactionBySendersAddressRequest)(nil), "blockchain.RawTransactionBySendersAddressRequest")
	proto.RegisterType((*RawTransactionRequest)(nil), "blockchain.RawTransactionRequest")
	proto.RegisterType((*RawTransactionReply)(nil), "blockchain.RawTransactionReply")
	proto.RegisterType((*SignTransactionRequest)(nil), "blockchain.SignTransactionRequest")
	proto.RegisterType((*SignTransactionBySecretKeyRequest)(nil), "blockchain.SignTransactionBySecretKeyRequest")
	proto.RegisterType((*SignTransactionReply)(nil), "blockchain.SignTransactionReply")
	proto.RegisterType((*SendTransactionRequest)(nil), "blockchain.SendTransactionRequest")
	proto.RegisterType((*SendTransactionReply)(nil), "blockchain.SendTransactionReply")
	proto.RegisterType((*GetTransactionStatusRequest)(nil), "blockchain.GetTransactionStatusRequest")
	proto.RegisterType((*GetTransactionStatusReply)(nil), "blockchain.GetTransactionStatusReply")
	proto.RegisterType((*TransactionByHashRequest)(nil), "blockchain.TransactionByHashRequest")
	proto.RegisterType((*TransactionByHashReply)(nil), "blockchain.TransactionByHashReply")
	proto.RegisterType((*InputOutput)(nil), "blockchain.InputOutput")
	proto.RegisterType((*CheckAddressRequest)(nil), "blockchain.CheckAddressRequest")
	proto.RegisterType((*GetAllBalanceRequest)(nil), "blockchain.GetAllBalanceRequest")
	proto.RegisterType((*GetAllBalanceReply)(nil), "blockchain.GetAllBalanceReply")
	proto.RegisterType((*GetAllBalanceReply_TokenBalance)(nil), "blockchain.GetAllBalanceReply.TokenBalance")
	proto.RegisterType((*GetUnspentInputsReply)(nil), "blockchain.GetUnspentInputsReply")
	proto.RegisterType((*UnspentInput)(nil), "blockchain.UnspentInput")
}

func init() { proto.RegisterFile("waves_adapter.proto", fileDescriptor_5065a9543fabcab5) }

var fileDescriptor_5065a9543fabcab5 = []byte{
	// 1180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x4b, 0x53, 0x1b, 0x47,
	0x10, 0xd6, 0x83, 0x67, 0x23, 0xf1, 0x18, 0x04, 0xd9, 0xac, 0xa9, 0x04, 0xa6, 0x4c, 0x85, 0xc2,
	0x44, 0x09, 0xb8, 0x72, 0x4d, 0x82, 0x5c, 0x46, 0x50, 0x4e, 0xd9, 0x78, 0x45, 0x9c, 0xca, 0x21,
	0xe5, 0x1a, 0x56, 0x63, 0xb4, 0x85, 0xd8, 0xdd, 0xec, 0x8e, 0x6c, 0x74, 0xca, 0x9f, 0xc9, 0x5f,
	0xc8, 0x35, 0x97, 0xfc, 0x97, 0xfc, 0x0e, 0xd7, 0x3c, 0x56, 0x9a, 0xd9, 0x17, 0xe2, 0xa4, 0xed,
	0x9e, 0xee, 0xaf, 0xbb, 0x67, 0xfa, 0x25, 0xd8, 0xfc, 0x44, 0x3e, 0xd2, 0xf8, 0x3d, 0xe9, 0x93,
	0x90, 0xd1, 0xa8, 0x1d, 0x46, 0x01, 0x0b, 0x10, 0x5c, 0x0f, 0x03, 0xf7, 0xd6, 0x1d, 0x10, 0xcf,
	0xc7, 0xab, 0xd0, 0xe8, 0x70, 0xca, 0xa1, 0x7f, 0x8e, 0x68, 0xcc, 0x30, 0x06, 0x50, 0x74, 0x38,
	0x1c, 0xa3, 0x16, 0xcc, 0x0b, 0x59, 0xab, 0xba, 0x5b, 0x3d, 0x58, 0x76, 0x24, 0x81, 0x0f, 0x61,
	0xf5, 0xb4, 0xdf, 0x8f, 0x68, 0x1c, 0x2b, 0x2d, 0x64, 0xc1, 0x22, 0x91, 0x1c, 0x25, 0x99, 0x90,
	0x1c, 0xff, 0xe5, 0x5d, 0xc8, 0xc6, 0x09, 0xbe, 0x03, 0x70, 0x46, 0x69, 0xa2, 0x77, 0x08, 0xeb,
	0x31, 0xf5, 0xfb, 0x34, 0x8a, 0x2f, 0x47, 0xd7, 0x43, 0xcf, 0x7d, 0x45, 0xc7, 0x0a, 0x20, 0xc3,
	0x17, 0x36, 0xe2, 0x98, 0xb2, 0x8b, 0xbe, 0x55, 0x53, 0x36, 0x24, 0x89, 0x77, 0x60, 0x49, 0x60,
	0x72, 0x8f, 0xd7, 0xa1, 0xfe, 0x81, 0x52, 0x05, 0xc2, 0x3f, 0xf1, 0x33, 0x58, 0xeb, 0x52, 0xd6,
	0x21, 0x43, 0xe2, 0xbb, 0x4a, 0xc8, 0x82, 0xc5, 0x6b, 0x49, 0x27, 0xee, 0x2a, 0x12, 0xff, 0x57,
	0x85, 0xcd, 0x2e, 0x65, 0xa7, 0xc3, 0xa1, 0x52, 0x88, 0xa5, 0xc6, 0x36, 0x2c, 0x90, 0xbb, 0x60,
	0xe4, 0x33, 0xa5, 0xa0, 0x28, 0xe4, 0x40, 0x53, 0x78, 0x91, 0x48, 0x5b, 0xb5, 0xdd, 0xfa, 0xc1,
	0xca, 0xc9, 0x51, 0x7b, 0x7a, 0xc5, 0xed, 0x1c, 0xbc, 0xf6, 0xa9, 0xa6, 0xe4, 0x98, 0x10, 0xf6,
	0xcf, 0xd0, 0xd0, 0x8f, 0xf5, 0xc0, 0xab, 0x46, 0xe0, 0x9a, 0x57, 0x35, 0xdd, 0x2b, 0xfc, 0x3d,
	0xb4, 0xba, 0xd4, 0xa7, 0x11, 0x61, 0x74, 0xf2, 0x50, 0x2a, 0xee, 0x82, 0x67, 0x3a, 0x82, 0xd6,
	0x3b, 0x32, 0xf4, 0xfa, 0x69, 0x8d, 0x16, 0xcc, 0x7f, 0xe4, 0x7c, 0x21, 0xbf, 0xe4, 0x48, 0x02,
	0xff, 0x05, 0xfb, 0x0e, 0xf9, 0x74, 0x15, 0x11, 0x3f, 0x26, 0x2e, 0xf3, 0x02, 0xbf, 0x33, 0xee,
	0xc9, 0xe7, 0x4a, 0xe5, 0xc5, 0x2e, 0xac, 0x28, 0x0b, 0x67, 0x51, 0x70, 0xa7, 0x8c, 0xea, 0x2c,
	0xb4, 0x03, 0xcb, 0x8a, 0xbc, 0x0a, 0x54, 0x14, 0x53, 0x86, 0x16, 0x60, 0xdd, 0x08, 0xf0, 0x9f,
	0x2a, 0x6c, 0x99, 0x1e, 0xcc, 0x6e, 0x31, 0x2f, 0xe7, 0x6a, 0x05, 0x39, 0x67, 0x78, 0x57, 0x2f,
	0xf6, 0x6e, 0xce, 0x48, 0x0a, 0xed, 0xc1, 0xe6, 0xcd, 0x4c, 0xdd, 0x87, 0xcd, 0xb4, 0xdb, 0xfc,
	0x96, 0x57, 0xa1, 0xc6, 0xee, 0x85, 0xaf, 0x0d, 0xa7, 0xc6, 0xee, 0xf1, 0x6b, 0xd8, 0xee, 0x79,
	0x37, 0x7e, 0x4e, 0x78, 0x4f, 0xa1, 0x29, 0x9d, 0x3c, 0x35, 0xde, 0xd1, 0x64, 0x2a, 0xbc, 0xda,
	0x04, 0xef, 0x0f, 0xd8, 0x4b, 0xe1, 0xf1, 0x07, 0x73, 0x23, 0xca, 0x5e, 0xd1, 0xa4, 0x32, 0xd1,
	0x01, 0xac, 0x49, 0x94, 0xc9, 0x89, 0x02, 0x4f, 0xb3, 0x33, 0xf0, 0x3f, 0x42, 0x2b, 0xe3, 0x6e,
	0x4e, 0x58, 0xfc, 0xbe, 0xd8, 0xfd, 0x39, 0x89, 0x07, 0x49, 0xba, 0x4a, 0x0a, 0x1f, 0xc0, 0x36,
	0x4f, 0x9f, 0x9c, 0x70, 0xd3, 0x17, 0x73, 0x08, 0xad, 0x8c, 0x24, 0xb7, 0x84, 0x60, 0x8e, 0xdd,
	0x4f, 0xea, 0x43, 0x7c, 0xe3, 0x63, 0x78, 0xd2, 0xa5, 0x4c, 0x13, 0xed, 0x31, 0xc2, 0x46, 0x93,
	0xd4, 0xcc, 0x53, 0x79, 0x0e, 0x5f, 0xe6, 0xab, 0xa8, 0x16, 0x10, 0x0b, 0x32, 0x69, 0x01, 0x92,
	0xc2, 0x27, 0x60, 0x19, 0x17, 0xcb, 0x43, 0x4a, 0x8c, 0x4c, 0x23, 0xae, 0x1a, 0x11, 0xff, 0x5d,
	0x87, 0xed, 0x1c, 0x25, 0x6e, 0x66, 0xb6, 0x17, 0x7e, 0x4c, 0x12, 0x1f, 0xc2, 0x7a, 0x44, 0x5d,
	0x2f, 0xf4, 0xa8, 0xcf, 0x12, 0x50, 0x99, 0xcb, 0x19, 0xfe, 0xe3, 0x53, 0x5a, 0x0b, 0x71, 0x41,
	0x0f, 0x31, 0x69, 0xc4, 0x8b, 0x93, 0x46, 0xcc, 0x6f, 0xbc, 0x4f, 0x18, 0xb1, 0x96, 0xc4, 0x73,
	0x8a, 0x6f, 0xed, 0x52, 0x97, 0xf5, 0x4b, 0x45, 0xdf, 0xc1, 0x82, 0xe7, 0x87, 0x23, 0x16, 0x5b,
	0x20, 0x1a, 0xea, 0x17, 0x7a, 0x43, 0xbd, 0xe0, 0x27, 0x6f, 0x46, 0x2c, 0x1c, 0x31, 0x47, 0x89,
	0xa1, 0x63, 0x58, 0x0c, 0x04, 0x27, 0xb6, 0x56, 0xca, 0x35, 0x12, 0x39, 0xd1, 0x2a, 0x78, 0x10,
	0xa7, 0x32, 0xe0, 0x86, 0x6a, 0x15, 0x53, 0x16, 0xfe, 0x09, 0x56, 0x34, 0xcd, 0xe2, 0xf6, 0x59,
	0xd8, 0x88, 0x2f, 0x60, 0xf3, 0xc5, 0x80, 0xba, 0xb7, 0xb3, 0x8e, 0xcb, 0x92, 0x21, 0xf7, 0x9a,
	0xf7, 0x74, 0x6d, 0x90, 0x3c, 0x8c, 0xb5, 0x03, 0xcb, 0x6e, 0xe0, 0xb3, 0x88, 0xb8, 0x4c, 0xce,
	0xa5, 0x65, 0x67, 0xca, 0xe0, 0x93, 0x0e, 0xa5, 0x00, 0xcb, 0x06, 0xdd, 0x5b, 0x68, 0xb2, 0xe0,
	0x96, 0xfa, 0xa9, 0x41, 0xf7, 0xac, 0x70, 0xd0, 0xc9, 0x39, 0x77, 0xa5, 0xe9, 0x38, 0x26, 0x82,
	0xdd, 0x81, 0x86, 0x7e, 0x8c, 0x6c, 0x58, 0x4a, 0xdc, 0x53, 0xc6, 0x27, 0x74, 0xe1, 0x05, 0xbf,
	0x84, 0xad, 0x2e, 0x65, 0xbf, 0xfa, 0x71, 0x48, 0x7d, 0x26, 0xde, 0x4a, 0x55, 0xeb, 0x11, 0xcc,
	0x8d, 0xd8, 0x7d, 0x60, 0x55, 0x85, 0x9b, 0x96, 0xee, 0xa6, 0x2e, 0xed, 0x08, 0x29, 0xfc, 0x7f,
	0x15, 0x1a, 0x3a, 0x9b, 0xe7, 0xea, 0x95, 0xd6, 0x1d, 0xf8, 0x37, 0xbf, 0xe9, 0xa4, 0x7c, 0xd4,
	0xdb, 0x24, 0x55, 0x83, 0x60, 0xee, 0x5d, 0x30, 0x92, 0x43, 0xaa, 0xe9, 0x88, 0x6f, 0x84, 0xa1,
	0xd1, 0x73, 0x23, 0x2f, 0x64, 0x97, 0xa3, 0x6b, 0x5e, 0x9d, 0xb2, 0x9e, 0x0c, 0x1e, 0x8f, 0x4a,
	0x25, 0x1f, 0x2f, 0xaa, 0x9a, 0xa3, 0x28, 0x7e, 0x13, 0x3d, 0xc2, 0x82, 0x78, 0xe0, 0xc5, 0xa2,
	0xaa, 0x9a, 0xce, 0x84, 0xe6, 0x3a, 0xe7, 0xd4, 0xbb, 0x19, 0x30, 0x51, 0x5a, 0x4d, 0x47, 0x51,
	0xbc, 0x6f, 0xbc, 0x08, 0xfc, 0x0f, 0x5e, 0x74, 0x47, 0x78, 0x4b, 0x89, 0x45, 0x99, 0x35, 0x1d,
	0x93, 0x79, 0xf2, 0x2f, 0xf0, 0x20, 0xc4, 0x32, 0x88, 0xce, 0x45, 0x02, 0xfc, 0x42, 0x62, 0x26,
	0x36, 0x3e, 0x85, 0x63, 0x5c, 0x95, 0xbe, 0x1a, 0xda, 0xdb, 0x39, 0x27, 0xe1, 0x70, 0x8c, 0x2b,
	0xe8, 0x0d, 0x5f, 0xb1, 0x8c, 0x7d, 0xc3, 0x84, 0xd1, 0x37, 0x40, 0x7b, 0xd7, 0x4c, 0x99, 0xec,
	0x9a, 0x82, 0x2b, 0xe8, 0x2d, 0xac, 0xa5, 0xd6, 0x11, 0x64, 0xeb, 0x6a, 0x66, 0x3d, 0x99, 0x90,
	0x79, 0x7b, 0x0c, 0xae, 0xa0, 0x1f, 0xa0, 0x7e, 0x46, 0x29, 0x32, 0x82, 0x98, 0x6e, 0xa2, 0x76,
	0x2b, 0xc3, 0x97, 0x6a, 0x5d, 0x80, 0xe9, 0xf6, 0x58, 0xea, 0xc4, 0x93, 0x54, 0x29, 0xe8, 0x75,
	0x80, 0x2b, 0x68, 0x0c, 0x7b, 0x5d, 0xca, 0xca, 0xd7, 0x26, 0x74, 0xac, 0x63, 0xcc, 0xb4, 0x62,
	0xd9, 0x5f, 0x17, 0xab, 0x24, 0xa6, 0x7f, 0x87, 0x8d, 0x8c, 0x69, 0xb4, 0x57, 0xa6, 0xf7, 0x08,
	0xe8, 0xb5, 0xd4, 0xe8, 0x47, 0x58, 0xd7, 0xca, 0x5f, 0x63, 0xcc, 0x07, 0xcb, 0xdb, 0x1d, 0x70,
	0x05, 0x05, 0x60, 0x17, 0x2f, 0x2d, 0xe8, 0xdb, 0x12, 0x84, 0xec, 0x72, 0x33, 0x93, 0x41, 0x1e,
	0x8b, 0xb9, 0x5c, 0xa4, 0x62, 0xc9, 0xdd, 0x51, 0x52, 0xd0, 0x39, 0xdb, 0x09, 0xae, 0xa0, 0x81,
	0x68, 0xde, 0x99, 0xc5, 0x02, 0x7d, 0x93, 0xca, 0x99, 0xa2, 0x6d, 0xc5, 0xde, 0x7f, 0x58, 0x50,
	0x5a, 0x7a, 0x0f, 0x1b, 0x99, 0xc5, 0x02, 0x3d, 0xd5, 0xb5, 0x8b, 0x96, 0x15, 0x1b, 0x3f, 0x20,
	0x25, 0x0d, 0xf4, 0xa0, 0xa1, 0x8f, 0x34, 0x64, 0x24, 0x49, 0xce, 0xb0, 0x9b, 0xa9, 0x38, 0x7b,
	0xd0, 0x34, 0x86, 0x07, 0xda, 0x2d, 0x99, 0x2b, 0x12, 0xf6, 0xab, 0xf2, 0xc9, 0x23, 0x40, 0xd7,
	0xd3, 0xb3, 0xa1, 0xb4, 0x80, 0xf7, 0x52, 0x88, 0xd9, 0xa9, 0x82, 0x2b, 0x9d, 0x23, 0xd8, 0xf2,
	0x82, 0xf6, 0x4d, 0x14, 0xba, 0xed, 0xe4, 0x4f, 0xb5, 0xf8, 0x8b, 0xdd, 0xd9, 0xf8, 0x8d, 0xff,
	0xa8, 0xde, 0x7a, 0xc9, 0xff, 0x67, 0x5f, 0x56, 0xaf, 0x17, 0xc4, 0x1f, 0xee, 0xe7, 0x9f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xf9, 0x4e, 0xf4, 0xa1, 0x87, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdapterClient interface {
	// getting last block
	GetLastBlockHeight(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error)
	// Generate address
	GenerateAddress(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GenerateAddressReply, error)
	// Validate address
	ValidateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error)
	// Get transaction's fee
	Fee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeReply, error)
	// Get account's balance
	GetBalance(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetBalanceReply, error)
	// request to create raw transaction by senders's address
	GetRawTransactionBySendersAddress(ctx context.Context, in *RawTransactionBySendersAddressRequest, opts ...grpc.CallOption) (*RawTransactionReply, error)
	// request to create raw transaction by senders's public key
	GetRawTransaction(ctx context.Context, in *RawTransactionRequest, opts ...grpc.CallOption) (*RawTransactionReply, error)
	// Sing transaction with private key keeped in adapter
	SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionReply, error)
	// Sing transaction by private key in parameters
	SignTransactionBySecretKey(ctx context.Context, in *SignTransactionBySecretKeyRequest, opts ...grpc.CallOption) (*SignTransactionReply, error)
	// Send transaction
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error)
	// Get transaction status
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusReply, error)
	// Get transaction
	TransactionByHash(ctx context.Context, in *TransactionByHashRequest, opts ...grpc.CallOption) (*TransactionByHashReply, error)
	// Check address
	CheckAddress(ctx context.Context, in *CheckAddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error)
	GetAllBalance(ctx context.Context, in *GetAllBalanceRequest, opts ...grpc.CallOption) (*GetAllBalanceReply, error)
	GetUnspentInputs(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetUnspentInputsReply, error)
}

type adapterClient struct {
	cc *grpc.ClientConn
}

func NewAdapterClient(cc *grpc.ClientConn) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) GetLastBlockHeight(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error) {
	out := new(BlockReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetLastBlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GenerateAddress(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GenerateAddressReply, error) {
	out := new(GenerateAddressReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GenerateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ValidateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error) {
	out := new(ValidateAddressReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/ValidateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Fee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeReply, error) {
	out := new(FeeReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/Fee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetBalance(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetBalanceReply, error) {
	out := new(GetBalanceReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetRawTransactionBySendersAddress(ctx context.Context, in *RawTransactionBySendersAddressRequest, opts ...grpc.CallOption) (*RawTransactionReply, error) {
	out := new(RawTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetRawTransactionBySendersAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetRawTransaction(ctx context.Context, in *RawTransactionRequest, opts ...grpc.CallOption) (*RawTransactionReply, error) {
	out := new(RawTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionReply, error) {
	out := new(SignTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SignTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SignTransactionBySecretKey(ctx context.Context, in *SignTransactionBySecretKeyRequest, opts ...grpc.CallOption) (*SignTransactionReply, error) {
	out := new(SignTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SignTransactionBySecretKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error) {
	out := new(SendTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusReply, error) {
	out := new(GetTransactionStatusReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) TransactionByHash(ctx context.Context, in *TransactionByHashRequest, opts ...grpc.CallOption) (*TransactionByHashReply, error) {
	out := new(TransactionByHashReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/TransactionByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) CheckAddress(ctx context.Context, in *CheckAddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error) {
	out := new(ValidateAddressReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/CheckAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetAllBalance(ctx context.Context, in *GetAllBalanceRequest, opts ...grpc.CallOption) (*GetAllBalanceReply, error) {
	out := new(GetAllBalanceReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetAllBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetUnspentInputs(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetUnspentInputsReply, error) {
	out := new(GetUnspentInputsReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetUnspentInputs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServer is the server API for Adapter service.
type AdapterServer interface {
	// getting last block
	GetLastBlockHeight(context.Context, *BlockRequest) (*BlockReply, error)
	// Generate address
	GenerateAddress(context.Context, *EmptyRequest) (*GenerateAddressReply, error)
	// Validate address
	ValidateAddress(context.Context, *AddressRequest) (*ValidateAddressReply, error)
	// Get transaction's fee
	Fee(context.Context, *FeeRequest) (*FeeReply, error)
	// Get account's balance
	GetBalance(context.Context, *AddressRequest) (*GetBalanceReply, error)
	// request to create raw transaction by senders's address
	GetRawTransactionBySendersAddress(context.Context, *RawTransactionBySendersAddressRequest) (*RawTransactionReply, error)
	// request to create raw transaction by senders's public key
	GetRawTransaction(context.Context, *RawTransactionRequest) (*RawTransactionReply, error)
	// Sing transaction with private key keeped in adapter
	SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionReply, error)
	// Sing transaction by private key in parameters
	SignTransactionBySecretKey(context.Context, *SignTransactionBySecretKeyRequest) (*SignTransactionReply, error)
	// Send transaction
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionReply, error)
	// Get transaction status
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*GetTransactionStatusReply, error)
	// Get transaction
	TransactionByHash(context.Context, *TransactionByHashRequest) (*TransactionByHashReply, error)
	// Check address
	CheckAddress(context.Context, *CheckAddressRequest) (*ValidateAddressReply, error)
	GetAllBalance(context.Context, *GetAllBalanceRequest) (*GetAllBalanceReply, error)
	GetUnspentInputs(context.Context, *AddressRequest) (*GetUnspentInputsReply, error)
}

// UnimplementedAdapterServer can be embedded to have forward compatible implementations.
type UnimplementedAdapterServer struct {
}

func (*UnimplementedAdapterServer) GetLastBlockHeight(ctx context.Context, req *BlockRequest) (*BlockReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastBlockHeight not implemented")
}
func (*UnimplementedAdapterServer) GenerateAddress(ctx context.Context, req *EmptyRequest) (*GenerateAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAddress not implemented")
}
func (*UnimplementedAdapterServer) ValidateAddress(ctx context.Context, req *AddressRequest) (*ValidateAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAddress not implemented")
}
func (*UnimplementedAdapterServer) Fee(ctx context.Context, req *FeeRequest) (*FeeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fee not implemented")
}
func (*UnimplementedAdapterServer) GetBalance(ctx context.Context, req *AddressRequest) (*GetBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedAdapterServer) GetRawTransactionBySendersAddress(ctx context.Context, req *RawTransactionBySendersAddressRequest) (*RawTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRawTransactionBySendersAddress not implemented")
}
func (*UnimplementedAdapterServer) GetRawTransaction(ctx context.Context, req *RawTransactionRequest) (*RawTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRawTransaction not implemented")
}
func (*UnimplementedAdapterServer) SignTransaction(ctx context.Context, req *SignTransactionRequest) (*SignTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTransaction not implemented")
}
func (*UnimplementedAdapterServer) SignTransactionBySecretKey(ctx context.Context, req *SignTransactionBySecretKeyRequest) (*SignTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTransactionBySecretKey not implemented")
}
func (*UnimplementedAdapterServer) SendTransaction(ctx context.Context, req *SendTransactionRequest) (*SendTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedAdapterServer) GetTransactionStatus(ctx context.Context, req *GetTransactionStatusRequest) (*GetTransactionStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (*UnimplementedAdapterServer) TransactionByHash(ctx context.Context, req *TransactionByHashRequest) (*TransactionByHashReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransactionByHash not implemented")
}
func (*UnimplementedAdapterServer) CheckAddress(ctx context.Context, req *CheckAddressRequest) (*ValidateAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAddress not implemented")
}
func (*UnimplementedAdapterServer) GetAllBalance(ctx context.Context, req *GetAllBalanceRequest) (*GetAllBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBalance not implemented")
}
func (*UnimplementedAdapterServer) GetUnspentInputs(ctx context.Context, req *AddressRequest) (*GetUnspentInputsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnspentInputs not implemented")
}

func RegisterAdapterServer(s *grpc.Server, srv AdapterServer) {
	s.RegisterService(&_Adapter_serviceDesc, srv)
}

func _Adapter_GetLastBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetLastBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetLastBlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetLastBlockHeight(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GenerateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GenerateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GenerateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GenerateAddress(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ValidateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ValidateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/ValidateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ValidateAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Fee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Fee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/Fee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Fee(ctx, req.(*FeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetBalance(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetRawTransactionBySendersAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransactionBySendersAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetRawTransactionBySendersAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetRawTransactionBySendersAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetRawTransactionBySendersAddress(ctx, req.(*RawTransactionBySendersAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetRawTransaction(ctx, req.(*RawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SignTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SignTransaction(ctx, req.(*SignTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SignTransactionBySecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionBySecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SignTransactionBySecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SignTransactionBySecretKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SignTransactionBySecretKey(ctx, req.(*SignTransactionBySecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_TransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).TransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/TransactionByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).TransactionByHash(ctx, req.(*TransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_CheckAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).CheckAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/CheckAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).CheckAddress(ctx, req.(*CheckAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetAllBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetAllBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetAllBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetAllBalance(ctx, req.(*GetAllBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetUnspentInputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetUnspentInputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetUnspentInputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetUnspentInputs(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Adapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastBlockHeight",
			Handler:    _Adapter_GetLastBlockHeight_Handler,
		},
		{
			MethodName: "GenerateAddress",
			Handler:    _Adapter_GenerateAddress_Handler,
		},
		{
			MethodName: "ValidateAddress",
			Handler:    _Adapter_ValidateAddress_Handler,
		},
		{
			MethodName: "Fee",
			Handler:    _Adapter_Fee_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Adapter_GetBalance_Handler,
		},
		{
			MethodName: "GetRawTransactionBySendersAddress",
			Handler:    _Adapter_GetRawTransactionBySendersAddress_Handler,
		},
		{
			MethodName: "GetRawTransaction",
			Handler:    _Adapter_GetRawTransaction_Handler,
		},
		{
			MethodName: "SignTransaction",
			Handler:    _Adapter_SignTransaction_Handler,
		},
		{
			MethodName: "SignTransactionBySecretKey",
			Handler:    _Adapter_SignTransactionBySecretKey_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Adapter_SendTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _Adapter_GetTransactionStatus_Handler,
		},
		{
			MethodName: "TransactionByHash",
			Handler:    _Adapter_TransactionByHash_Handler,
		},
		{
			MethodName: "CheckAddress",
			Handler:    _Adapter_CheckAddress_Handler,
		},
		{
			MethodName: "GetAllBalance",
			Handler:    _Adapter_GetAllBalance_Handler,
		},
		{
			MethodName: "GetUnspentInputs",
			Handler:    _Adapter_GetUnspentInputs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "waves_adapter.proto",
}
