// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waves_adapter.proto

package blockchain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message for getting last block
type BlockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{0}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

// The response message containing last block number
type BlockReply struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockReply) Reset()         { *m = BlockReply{} }
func (m *BlockReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply) ProtoMessage()    {}
func (*BlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{1}
}

func (m *BlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply.Unmarshal(m, b)
}
func (m *BlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply.Marshal(b, m, deterministic)
}
func (m *BlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply.Merge(m, src)
}
func (m *BlockReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply.Size(m)
}
func (m *BlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply proto.InternalMessageInfo

func (m *BlockReply) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

// The request message for getting information by account address
type AddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressRequest) Reset()         { *m = AddressRequest{} }
func (m *AddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()    {}
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{2}
}

func (m *AddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressRequest.Unmarshal(m, b)
}
func (m *AddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressRequest.Marshal(b, m, deterministic)
}
func (m *AddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressRequest.Merge(m, src)
}
func (m *AddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddressRequest.Size(m)
}
func (m *AddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressRequest proto.InternalMessageInfo

func (m *AddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// empty request message
type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{3}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

// fee request message
type FeeRequest struct {
	SendersPublicKey     string   `protobuf:"bytes,1,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeRequest) Reset()         { *m = FeeRequest{} }
func (m *FeeRequest) String() string { return proto.CompactTextString(m) }
func (*FeeRequest) ProtoMessage()    {}
func (*FeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{4}
}

func (m *FeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeRequest.Unmarshal(m, b)
}
func (m *FeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeRequest.Marshal(b, m, deterministic)
}
func (m *FeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRequest.Merge(m, src)
}
func (m *FeeRequest) XXX_Size() int {
	return xxx_messageInfo_FeeRequest.Size(m)
}
func (m *FeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRequest proto.InternalMessageInfo

func (m *FeeRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *FeeRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// The response message containing transaction's fee
type FeeReply struct {
	Fee                  string   `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeReply) Reset()         { *m = FeeReply{} }
func (m *FeeReply) String() string { return proto.CompactTextString(m) }
func (*FeeReply) ProtoMessage()    {}
func (*FeeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{5}
}

func (m *FeeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeReply.Unmarshal(m, b)
}
func (m *FeeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeReply.Marshal(b, m, deterministic)
}
func (m *FeeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeReply.Merge(m, src)
}
func (m *FeeReply) XXX_Size() int {
	return xxx_messageInfo_FeeReply.Size(m)
}
func (m *FeeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeReply.DiscardUnknown(m)
}

var xxx_messageInfo_FeeReply proto.InternalMessageInfo

func (m *FeeReply) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

// The response message containing account's balance
type GetBalanceReply struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceReply) Reset()         { *m = GetBalanceReply{} }
func (m *GetBalanceReply) String() string { return proto.CompactTextString(m) }
func (*GetBalanceReply) ProtoMessage()    {}
func (*GetBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{6}
}

func (m *GetBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceReply.Unmarshal(m, b)
}
func (m *GetBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceReply.Marshal(b, m, deterministic)
}
func (m *GetBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceReply.Merge(m, src)
}
func (m *GetBalanceReply) XXX_Size() int {
	return xxx_messageInfo_GetBalanceReply.Size(m)
}
func (m *GetBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceReply proto.InternalMessageInfo

func (m *GetBalanceReply) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

// The response message containing account's balance with assets balances
type GetAllBalancesReply struct {
	Amount               string                              `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetBalances        []*GetAllBalancesReply_AssetBalance `protobuf:"bytes,2,rep,name=assetBalances,proto3" json:"assetBalances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetAllBalancesReply) Reset()         { *m = GetAllBalancesReply{} }
func (m *GetAllBalancesReply) String() string { return proto.CompactTextString(m) }
func (*GetAllBalancesReply) ProtoMessage()    {}
func (*GetAllBalancesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{7}
}

func (m *GetAllBalancesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalancesReply.Unmarshal(m, b)
}
func (m *GetAllBalancesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalancesReply.Marshal(b, m, deterministic)
}
func (m *GetAllBalancesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalancesReply.Merge(m, src)
}
func (m *GetAllBalancesReply) XXX_Size() int {
	return xxx_messageInfo_GetAllBalancesReply.Size(m)
}
func (m *GetAllBalancesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalancesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalancesReply proto.InternalMessageInfo

func (m *GetAllBalancesReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetAllBalancesReply) GetAssetBalances() []*GetAllBalancesReply_AssetBalance {
	if m != nil {
		return m.AssetBalances
	}
	return nil
}

type GetAllBalancesReply_AssetBalance struct {
	AssetId              string   `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBalancesReply_AssetBalance) Reset()         { *m = GetAllBalancesReply_AssetBalance{} }
func (m *GetAllBalancesReply_AssetBalance) String() string { return proto.CompactTextString(m) }
func (*GetAllBalancesReply_AssetBalance) ProtoMessage()    {}
func (*GetAllBalancesReply_AssetBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{7, 0}
}

func (m *GetAllBalancesReply_AssetBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Unmarshal(m, b)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Marshal(b, m, deterministic)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalancesReply_AssetBalance.Merge(m, src)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Size() int {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Size(m)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalancesReply_AssetBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalancesReply_AssetBalance proto.InternalMessageInfo

func (m *GetAllBalancesReply_AssetBalance) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *GetAllBalancesReply_AssetBalance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The response message containing generated address
type GenerateAddressReply struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressReply) Reset()         { *m = GenerateAddressReply{} }
func (m *GenerateAddressReply) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressReply) ProtoMessage()    {}
func (*GenerateAddressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{8}
}

func (m *GenerateAddressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressReply.Unmarshal(m, b)
}
func (m *GenerateAddressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressReply.Marshal(b, m, deterministic)
}
func (m *GenerateAddressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressReply.Merge(m, src)
}
func (m *GenerateAddressReply) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressReply.Size(m)
}
func (m *GenerateAddressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressReply proto.InternalMessageInfo

func (m *GenerateAddressReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// The response message containing result of address's validation
type ValidateAddressReply struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressReply) Reset()         { *m = ValidateAddressReply{} }
func (m *ValidateAddressReply) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressReply) ProtoMessage()    {}
func (*ValidateAddressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{9}
}

func (m *ValidateAddressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressReply.Unmarshal(m, b)
}
func (m *ValidateAddressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressReply.Marshal(b, m, deterministic)
}
func (m *ValidateAddressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressReply.Merge(m, src)
}
func (m *ValidateAddressReply) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressReply.Size(m)
}
func (m *ValidateAddressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressReply proto.InternalMessageInfo

func (m *ValidateAddressReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// The request message for raw transaction creation
type RawTransactionBySendersAddressRequest struct {
	AddressFrom          string   `protobuf:"bytes,1,opt,name=addressFrom,proto3" json:"addressFrom,omitempty"`
	AddressTo            string   `protobuf:"bytes,2,opt,name=addressTo,proto3" json:"addressTo,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionBySendersAddressRequest) Reset()         { *m = RawTransactionBySendersAddressRequest{} }
func (m *RawTransactionBySendersAddressRequest) String() string { return proto.CompactTextString(m) }
func (*RawTransactionBySendersAddressRequest) ProtoMessage()    {}
func (*RawTransactionBySendersAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{10}
}

func (m *RawTransactionBySendersAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionBySendersAddressRequest.Unmarshal(m, b)
}
func (m *RawTransactionBySendersAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionBySendersAddressRequest.Marshal(b, m, deterministic)
}
func (m *RawTransactionBySendersAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionBySendersAddressRequest.Merge(m, src)
}
func (m *RawTransactionBySendersAddressRequest) XXX_Size() int {
	return xxx_messageInfo_RawTransactionBySendersAddressRequest.Size(m)
}
func (m *RawTransactionBySendersAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionBySendersAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionBySendersAddressRequest proto.InternalMessageInfo

func (m *RawTransactionBySendersAddressRequest) GetAddressFrom() string {
	if m != nil {
		return m.AddressFrom
	}
	return ""
}

func (m *RawTransactionBySendersAddressRequest) GetAddressTo() string {
	if m != nil {
		return m.AddressTo
	}
	return ""
}

func (m *RawTransactionBySendersAddressRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The request message for raw transaction creation
type RawTransactionBySendersPublicKeyRequest struct {
	SendersPublicKey     string   `protobuf:"bytes,1,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AddressTo            string   `protobuf:"bytes,2,opt,name=addressTo,proto3" json:"addressTo,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId              string   `protobuf:"bytes,4,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionBySendersPublicKeyRequest) Reset() {
	*m = RawTransactionBySendersPublicKeyRequest{}
}
func (m *RawTransactionBySendersPublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*RawTransactionBySendersPublicKeyRequest) ProtoMessage()    {}
func (*RawTransactionBySendersPublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{11}
}

func (m *RawTransactionBySendersPublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionBySendersPublicKeyRequest.Unmarshal(m, b)
}
func (m *RawTransactionBySendersPublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionBySendersPublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *RawTransactionBySendersPublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionBySendersPublicKeyRequest.Merge(m, src)
}
func (m *RawTransactionBySendersPublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_RawTransactionBySendersPublicKeyRequest.Size(m)
}
func (m *RawTransactionBySendersPublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionBySendersPublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionBySendersPublicKeyRequest proto.InternalMessageInfo

func (m *RawTransactionBySendersPublicKeyRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *RawTransactionBySendersPublicKeyRequest) GetAddressTo() string {
	if m != nil {
		return m.AddressTo
	}
	return ""
}

func (m *RawTransactionBySendersPublicKeyRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RawTransactionBySendersPublicKeyRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// The response message containing raw transaction
type RawTransactionReply struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionReply) Reset()         { *m = RawTransactionReply{} }
func (m *RawTransactionReply) String() string { return proto.CompactTextString(m) }
func (*RawTransactionReply) ProtoMessage()    {}
func (*RawTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{12}
}

func (m *RawTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionReply.Unmarshal(m, b)
}
func (m *RawTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionReply.Marshal(b, m, deterministic)
}
func (m *RawTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionReply.Merge(m, src)
}
func (m *RawTransactionReply) XXX_Size() int {
	return xxx_messageInfo_RawTransactionReply.Size(m)
}
func (m *RawTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionReply proto.InternalMessageInfo

func (m *RawTransactionReply) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The request message for singing transaction
type SignTransactionRequest struct {
	SenderAddress        string   `protobuf:"bytes,1,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	Tx                   []byte   `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionRequest) Reset()         { *m = SignTransactionRequest{} }
func (m *SignTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SignTransactionRequest) ProtoMessage()    {}
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{13}
}

func (m *SignTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionRequest.Unmarshal(m, b)
}
func (m *SignTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SignTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionRequest.Merge(m, src)
}
func (m *SignTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SignTransactionRequest.Size(m)
}
func (m *SignTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionRequest proto.InternalMessageInfo

func (m *SignTransactionRequest) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *SignTransactionRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The request message for singing transaction by private key in parameters
type SignTransactionBySecretKeyRequest struct {
	SenderSecretKey      string   `protobuf:"bytes,1,opt,name=senderSecretKey,proto3" json:"senderSecretKey,omitempty"`
	Tx                   []byte   `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionBySecretKeyRequest) Reset()         { *m = SignTransactionBySecretKeyRequest{} }
func (m *SignTransactionBySecretKeyRequest) String() string { return proto.CompactTextString(m) }
func (*SignTransactionBySecretKeyRequest) ProtoMessage()    {}
func (*SignTransactionBySecretKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{14}
}

func (m *SignTransactionBySecretKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionBySecretKeyRequest.Unmarshal(m, b)
}
func (m *SignTransactionBySecretKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionBySecretKeyRequest.Marshal(b, m, deterministic)
}
func (m *SignTransactionBySecretKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionBySecretKeyRequest.Merge(m, src)
}
func (m *SignTransactionBySecretKeyRequest) XXX_Size() int {
	return xxx_messageInfo_SignTransactionBySecretKeyRequest.Size(m)
}
func (m *SignTransactionBySecretKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionBySecretKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionBySecretKeyRequest proto.InternalMessageInfo

func (m *SignTransactionBySecretKeyRequest) GetSenderSecretKey() string {
	if m != nil {
		return m.SenderSecretKey
	}
	return ""
}

func (m *SignTransactionBySecretKeyRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The response message containing signed transaction
type SignTransactionReply struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionReply) Reset()         { *m = SignTransactionReply{} }
func (m *SignTransactionReply) String() string { return proto.CompactTextString(m) }
func (*SignTransactionReply) ProtoMessage()    {}
func (*SignTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{15}
}

func (m *SignTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionReply.Unmarshal(m, b)
}
func (m *SignTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionReply.Marshal(b, m, deterministic)
}
func (m *SignTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionReply.Merge(m, src)
}
func (m *SignTransactionReply) XXX_Size() int {
	return xxx_messageInfo_SignTransactionReply.Size(m)
}
func (m *SignTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionReply proto.InternalMessageInfo

func (m *SignTransactionReply) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The request message for singing transaction
type SendTransactionRequest struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{16}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The response message containing transaction's id
type SendTransactionReply struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionReply) Reset()         { *m = SendTransactionReply{} }
func (m *SendTransactionReply) String() string { return proto.CompactTextString(m) }
func (*SendTransactionReply) ProtoMessage()    {}
func (*SendTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{17}
}

func (m *SendTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionReply.Unmarshal(m, b)
}
func (m *SendTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionReply.Marshal(b, m, deterministic)
}
func (m *SendTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionReply.Merge(m, src)
}
func (m *SendTransactionReply) XXX_Size() int {
	return xxx_messageInfo_SendTransactionReply.Size(m)
}
func (m *SendTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionReply proto.InternalMessageInfo

func (m *SendTransactionReply) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// The request message for getting transaction's status containing tx id
type GetTransactionStatusRequest struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionStatusRequest) Reset()         { *m = GetTransactionStatusRequest{} }
func (m *GetTransactionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusRequest) ProtoMessage()    {}
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{18}
}

func (m *GetTransactionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusRequest.Unmarshal(m, b)
}
func (m *GetTransactionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusRequest.Merge(m, src)
}
func (m *GetTransactionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusRequest.Size(m)
}
func (m *GetTransactionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusRequest proto.InternalMessageInfo

func (m *GetTransactionStatusRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// The response message containing transaction's status: UNKNOWN, PENDING, SUCCESS
type GetTransactionStatusReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionStatusReply) Reset()         { *m = GetTransactionStatusReply{} }
func (m *GetTransactionStatusReply) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusReply) ProtoMessage()    {}
func (*GetTransactionStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5065a9543fabcab5, []int{19}
}

func (m *GetTransactionStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusReply.Unmarshal(m, b)
}
func (m *GetTransactionStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusReply.Marshal(b, m, deterministic)
}
func (m *GetTransactionStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusReply.Merge(m, src)
}
func (m *GetTransactionStatusReply) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusReply.Size(m)
}
func (m *GetTransactionStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusReply proto.InternalMessageInfo

func (m *GetTransactionStatusReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockRequest)(nil), "blockchain.BlockRequest")
	proto.RegisterType((*BlockReply)(nil), "blockchain.BlockReply")
	proto.RegisterType((*AddressRequest)(nil), "blockchain.AddressRequest")
	proto.RegisterType((*EmptyRequest)(nil), "blockchain.EmptyRequest")
	proto.RegisterType((*FeeRequest)(nil), "blockchain.FeeRequest")
	proto.RegisterType((*FeeReply)(nil), "blockchain.FeeReply")
	proto.RegisterType((*GetBalanceReply)(nil), "blockchain.GetBalanceReply")
	proto.RegisterType((*GetAllBalancesReply)(nil), "blockchain.GetAllBalancesReply")
	proto.RegisterType((*GetAllBalancesReply_AssetBalance)(nil), "blockchain.GetAllBalancesReply.AssetBalance")
	proto.RegisterType((*GenerateAddressReply)(nil), "blockchain.GenerateAddressReply")
	proto.RegisterType((*ValidateAddressReply)(nil), "blockchain.ValidateAddressReply")
	proto.RegisterType((*RawTransactionBySendersAddressRequest)(nil), "blockchain.RawTransactionBySendersAddressRequest")
	proto.RegisterType((*RawTransactionBySendersPublicKeyRequest)(nil), "blockchain.RawTransactionBySendersPublicKeyRequest")
	proto.RegisterType((*RawTransactionReply)(nil), "blockchain.RawTransactionReply")
	proto.RegisterType((*SignTransactionRequest)(nil), "blockchain.SignTransactionRequest")
	proto.RegisterType((*SignTransactionBySecretKeyRequest)(nil), "blockchain.SignTransactionBySecretKeyRequest")
	proto.RegisterType((*SignTransactionReply)(nil), "blockchain.SignTransactionReply")
	proto.RegisterType((*SendTransactionRequest)(nil), "blockchain.SendTransactionRequest")
	proto.RegisterType((*SendTransactionReply)(nil), "blockchain.SendTransactionReply")
	proto.RegisterType((*GetTransactionStatusRequest)(nil), "blockchain.GetTransactionStatusRequest")
	proto.RegisterType((*GetTransactionStatusReply)(nil), "blockchain.GetTransactionStatusReply")
}

func init() { proto.RegisterFile("waves_adapter.proto", fileDescriptor_5065a9543fabcab5) }

var fileDescriptor_5065a9543fabcab5 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xcd, 0x4f, 0x7f, 0xa7, 0x6d, 0xd2, 0x6f, 0xeb, 0x2f, 0x0a, 0x6e, 0x25, 0xd2, 0x85, 0xd2,
	0xa8, 0x94, 0x88, 0xb6, 0xe2, 0x9e, 0x44, 0xa2, 0x2e, 0x02, 0x41, 0x71, 0x2b, 0x10, 0x17, 0x08,
	0x6d, 0x9c, 0xa5, 0xb5, 0x70, 0xed, 0x60, 0x6f, 0xda, 0xe6, 0x02, 0xf1, 0x34, 0x3c, 0x09, 0x8f,
	0xc0, 0x0b, 0x21, 0xef, 0xae, 0x93, 0x5d, 0xdb, 0x49, 0xa3, 0x5e, 0x35, 0x33, 0x9e, 0x39, 0x73,
	0x66, 0x77, 0xe6, 0x74, 0x61, 0xe3, 0x86, 0x5c, 0xd3, 0xe8, 0x2b, 0xe9, 0x91, 0x3e, 0xa3, 0x61,
	0xab, 0x1f, 0x06, 0x2c, 0x40, 0xd0, 0xf5, 0x02, 0xe7, 0xbb, 0x73, 0x49, 0x5c, 0x1f, 0x57, 0x60,
	0xb5, 0x13, 0x5b, 0x36, 0xfd, 0x31, 0xa0, 0x11, 0xc3, 0x18, 0x40, 0xda, 0x7d, 0x6f, 0x88, 0x0c,
	0x98, 0xe7, 0xb1, 0xf5, 0x62, 0xa3, 0xd8, 0x5c, 0xb6, 0x85, 0x81, 0xf7, 0xa0, 0xd2, 0xee, 0xf5,
	0x42, 0x1a, 0x45, 0x32, 0x0b, 0xd5, 0x61, 0x91, 0x08, 0x8f, 0x8c, 0x4c, 0xcc, 0x18, 0xff, 0xd5,
	0x55, 0x9f, 0x0d, 0x13, 0x7c, 0x1b, 0xe0, 0x98, 0xd2, 0x24, 0x6f, 0x0f, 0xd6, 0x23, 0xea, 0xf7,
	0x68, 0x18, 0x9d, 0x0e, 0xba, 0x9e, 0xeb, 0xbc, 0xa1, 0x43, 0x09, 0x90, 0xf1, 0xf3, 0x1a, 0x51,
	0x44, 0xd9, 0xeb, 0x5e, 0xbd, 0x24, 0x6b, 0x08, 0x13, 0x6f, 0xc1, 0x12, 0xc7, 0x8c, 0x19, 0xaf,
	0x43, 0xf9, 0x1b, 0xa5, 0x12, 0x24, 0xfe, 0x89, 0x9f, 0x42, 0xd5, 0xa2, 0xac, 0x43, 0x3c, 0xe2,
	0x3b, 0x32, 0xa8, 0x0e, 0x8b, 0x5d, 0x61, 0x27, 0x74, 0xa5, 0x89, 0xff, 0x14, 0x61, 0xc3, 0xa2,
	0xac, 0xed, 0x79, 0x32, 0x21, 0x12, 0x19, 0x35, 0x58, 0x20, 0x57, 0xc1, 0xc0, 0x67, 0x32, 0x41,
	0x5a, 0xc8, 0x86, 0x35, 0xce, 0x22, 0x89, 0xae, 0x97, 0x1a, 0xe5, 0xe6, 0xca, 0xe1, 0x7e, 0x6b,
	0x7c, 0xc4, 0xad, 0x1c, 0xbc, 0x56, 0x5b, 0x49, 0xb2, 0x75, 0x08, 0xf3, 0x25, 0xac, 0xaa, 0x9f,
	0xd5, 0xc6, 0x8b, 0x5a, 0xe3, 0x0a, 0xab, 0x92, 0xca, 0x0a, 0x3f, 0x07, 0xc3, 0xa2, 0x3e, 0x0d,
	0x09, 0xa3, 0xa3, 0x8b, 0x92, 0x7d, 0x4f, 0xb8, 0xa6, 0x7d, 0x30, 0x3e, 0x12, 0xcf, 0xed, 0xa5,
	0x33, 0x0c, 0x98, 0xbf, 0x8e, 0xfd, 0x3c, 0x7e, 0xc9, 0x16, 0x06, 0xfe, 0x05, 0x3b, 0x36, 0xb9,
	0x39, 0x0f, 0x89, 0x1f, 0x11, 0x87, 0xb9, 0x81, 0xdf, 0x19, 0x9e, 0x89, 0xeb, 0x4a, 0xcd, 0x45,
	0x03, 0x56, 0x64, 0x85, 0xe3, 0x30, 0xb8, 0x92, 0x45, 0x55, 0x17, 0xda, 0x82, 0x65, 0x69, 0x9e,
	0x07, 0xb2, 0x8b, 0xb1, 0x43, 0x69, 0xb0, 0xac, 0x35, 0xf8, 0xbb, 0x08, 0xbb, 0x13, 0x18, 0x8c,
	0x06, 0xe6, 0x3e, 0x33, 0x76, 0x2f, 0x36, 0xea, 0x05, 0xcd, 0xe9, 0x93, 0xb9, 0x03, 0x1b, 0x3a,
	0x4d, 0x71, 0xaa, 0x15, 0x28, 0xb1, 0x5b, 0x4e, 0x62, 0xd5, 0x2e, 0xb1, 0x5b, 0xfc, 0x0e, 0x6a,
	0x67, 0xee, 0x85, 0xaf, 0xc5, 0x09, 0xf2, 0x8f, 0x61, 0x4d, 0x90, 0x6c, 0x6b, 0xf7, 0xa6, 0x3b,
	0x25, 0x5e, 0x69, 0x84, 0xf7, 0x05, 0xb6, 0x53, 0x78, 0xf1, 0xf1, 0x38, 0x21, 0x65, 0xca, 0xb9,
	0x34, 0xa1, 0x2a, 0x50, 0x46, 0x5f, 0x24, 0x78, 0xda, 0x9d, 0x81, 0x7f, 0x02, 0x46, 0x86, 0x6e,
	0x5e, 0x5b, 0x4d, 0xa8, 0xc5, 0x97, 0x92, 0xd3, 0x56, 0x3a, 0x72, 0x0f, 0x8c, 0x4c, 0x64, 0x8c,
	0x88, 0x60, 0x8e, 0xdd, 0x8e, 0xe6, 0x9e, 0xff, 0xc6, 0x07, 0xb0, 0x69, 0x51, 0xa6, 0x84, 0x9e,
	0x31, 0xc2, 0x06, 0xa3, 0x91, 0xcb, 0x4b, 0x39, 0x82, 0x07, 0xf9, 0x29, 0x72, 0xb5, 0x23, 0x6e,
	0x26, 0xab, 0x2d, 0xac, 0xc3, 0xbf, 0x4b, 0xb0, 0xd8, 0x16, 0xba, 0x89, 0x4e, 0x00, 0x59, 0x94,
	0xbd, 0x25, 0x11, 0xe3, 0xe2, 0x78, 0x42, 0xdd, 0x8b, 0x4b, 0x86, 0xea, 0xea, 0x96, 0xab, 0x2a,
	0x6a, 0xd6, 0x72, 0xbe, 0xf4, 0xbd, 0x21, 0x2e, 0xa0, 0xf7, 0xb1, 0x1a, 0x69, 0xab, 0xa9, 0xc3,
	0xa8, 0x62, 0x69, 0x36, 0x74, 0x19, 0xc9, 0x6e, 0x34, 0x2e, 0xa0, 0x0f, 0x50, 0x4d, 0x6d, 0x2e,
	0x32, 0xd5, 0x34, 0x7d, 0x23, 0x75, 0xc8, 0xbc, 0x95, 0xc7, 0x05, 0xf4, 0x02, 0xca, 0xc7, 0x94,
	0x22, 0xad, 0x89, 0xb1, 0x68, 0x9b, 0x46, 0xc6, 0x2f, 0xd2, 0x2c, 0x80, 0xb1, 0xd0, 0x4e, 0x25,
	0xb1, 0x99, 0x92, 0x47, 0x55, 0x9c, 0xf9, 0x19, 0x55, 0x74, 0xcd, 0x9c, 0x0a, 0xf6, 0xf0, 0x0e,
	0xad, 0xc5, 0x05, 0x34, 0x84, 0x6d, 0x8b, 0xb2, 0xe9, 0x92, 0x85, 0x0e, 0x54, 0x9c, 0x99, 0xe4,
	0x4d, 0x2f, 0x9d, 0xb3, 0xe8, 0xb8, 0x80, 0x7e, 0xc2, 0xa3, 0xc9, 0xa5, 0xc7, 0xc2, 0x73, 0x34,
	0x43, 0xf1, 0xb4, 0xb2, 0xcd, 0x52, 0xfe, 0x33, 0x54, 0x53, 0xab, 0x8a, 0xb0, 0x9a, 0x95, 0x2f,
	0x3b, 0xfa, 0x94, 0xe4, 0xed, 0x3a, 0x2e, 0xa0, 0x00, 0xcc, 0xc9, 0x22, 0x83, 0x9e, 0x4d, 0x41,
	0xc8, 0x8a, 0xd1, 0x4c, 0x05, 0xe3, 0x5e, 0x74, 0x91, 0x48, 0xf5, 0x92, 0xab, 0x35, 0x29, 0xe8,
	0x1c, 0x95, 0xc1, 0x05, 0x74, 0x19, 0xff, 0xc3, 0xcc, 0x0a, 0x04, 0xda, 0x4d, 0xcd, 0xd6, 0x24,
	0xd5, 0x31, 0x77, 0xee, 0x0e, 0xe4, 0x95, 0x3a, 0xfb, 0xf0, 0xbf, 0x1b, 0xb4, 0x2e, 0xc2, 0xbe,
	0xd3, 0x4a, 0x1e, 0x65, 0xfc, 0x89, 0xd6, 0xf9, 0xef, 0x53, 0xfc, 0x47, 0x0a, 0xce, 0x69, 0xfc,
	0x4e, 0x3b, 0x2d, 0x76, 0x17, 0xf8, 0x83, 0xed, 0xe8, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0x8e, 0xed, 0xfb, 0xc7, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdapterClient interface {
	// getting last block
	GetLastBlockHeight(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error)
	// Generate address
	GenerateAddress(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GenerateAddressReply, error)
	// Validate address
	ValidateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error)
	// Get transaction's fee
	Fee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeReply, error)
	// Get account's balance
	GetBalance(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetBalanceReply, error)
	// Get account's balance with assets balances
	GetAllBalances(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetAllBalancesReply, error)
	// request to create raw transaction by senders's address
	GetRawTransactionBySendersAddress(ctx context.Context, in *RawTransactionBySendersAddressRequest, opts ...grpc.CallOption) (*RawTransactionReply, error)
	// request to create raw transaction by senders's public key
	GetRawTransactionBySendersPublicKey(ctx context.Context, in *RawTransactionBySendersPublicKeyRequest, opts ...grpc.CallOption) (*RawTransactionReply, error)
	// Sing transaction with private key keeped in adapter
	SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionReply, error)
	// Sing transaction by private key in parameters
	SignTransactionBySecretKey(ctx context.Context, in *SignTransactionBySecretKeyRequest, opts ...grpc.CallOption) (*SignTransactionReply, error)
	// Send transaction
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error)
	// Get transaction status
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusReply, error)
}

type adapterClient struct {
	cc *grpc.ClientConn
}

func NewAdapterClient(cc *grpc.ClientConn) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) GetLastBlockHeight(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error) {
	out := new(BlockReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetLastBlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GenerateAddress(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GenerateAddressReply, error) {
	out := new(GenerateAddressReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GenerateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ValidateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error) {
	out := new(ValidateAddressReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/ValidateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Fee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeReply, error) {
	out := new(FeeReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/Fee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetBalance(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetBalanceReply, error) {
	out := new(GetBalanceReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetAllBalances(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetAllBalancesReply, error) {
	out := new(GetAllBalancesReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetAllBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetRawTransactionBySendersAddress(ctx context.Context, in *RawTransactionBySendersAddressRequest, opts ...grpc.CallOption) (*RawTransactionReply, error) {
	out := new(RawTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetRawTransactionBySendersAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetRawTransactionBySendersPublicKey(ctx context.Context, in *RawTransactionBySendersPublicKeyRequest, opts ...grpc.CallOption) (*RawTransactionReply, error) {
	out := new(RawTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetRawTransactionBySendersPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionReply, error) {
	out := new(SignTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SignTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SignTransactionBySecretKey(ctx context.Context, in *SignTransactionBySecretKeyRequest, opts ...grpc.CallOption) (*SignTransactionReply, error) {
	out := new(SignTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SignTransactionBySecretKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error) {
	out := new(SendTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusReply, error) {
	out := new(GetTransactionStatusReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServer is the server API for Adapter service.
type AdapterServer interface {
	// getting last block
	GetLastBlockHeight(context.Context, *BlockRequest) (*BlockReply, error)
	// Generate address
	GenerateAddress(context.Context, *EmptyRequest) (*GenerateAddressReply, error)
	// Validate address
	ValidateAddress(context.Context, *AddressRequest) (*ValidateAddressReply, error)
	// Get transaction's fee
	Fee(context.Context, *FeeRequest) (*FeeReply, error)
	// Get account's balance
	GetBalance(context.Context, *AddressRequest) (*GetBalanceReply, error)
	// Get account's balance with assets balances
	GetAllBalances(context.Context, *AddressRequest) (*GetAllBalancesReply, error)
	// request to create raw transaction by senders's address
	GetRawTransactionBySendersAddress(context.Context, *RawTransactionBySendersAddressRequest) (*RawTransactionReply, error)
	// request to create raw transaction by senders's public key
	GetRawTransactionBySendersPublicKey(context.Context, *RawTransactionBySendersPublicKeyRequest) (*RawTransactionReply, error)
	// Sing transaction with private key keeped in adapter
	SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionReply, error)
	// Sing transaction by private key in parameters
	SignTransactionBySecretKey(context.Context, *SignTransactionBySecretKeyRequest) (*SignTransactionReply, error)
	// Send transaction
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionReply, error)
	// Get transaction status
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*GetTransactionStatusReply, error)
}

func RegisterAdapterServer(s *grpc.Server, srv AdapterServer) {
	s.RegisterService(&_Adapter_serviceDesc, srv)
}

func _Adapter_GetLastBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetLastBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetLastBlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetLastBlockHeight(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GenerateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GenerateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GenerateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GenerateAddress(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ValidateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ValidateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/ValidateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ValidateAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Fee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Fee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/Fee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Fee(ctx, req.(*FeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetBalance(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetAllBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetAllBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetAllBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetAllBalances(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetRawTransactionBySendersAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransactionBySendersAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetRawTransactionBySendersAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetRawTransactionBySendersAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetRawTransactionBySendersAddress(ctx, req.(*RawTransactionBySendersAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetRawTransactionBySendersPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransactionBySendersPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetRawTransactionBySendersPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetRawTransactionBySendersPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetRawTransactionBySendersPublicKey(ctx, req.(*RawTransactionBySendersPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SignTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SignTransaction(ctx, req.(*SignTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SignTransactionBySecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionBySecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SignTransactionBySecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SignTransactionBySecretKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SignTransactionBySecretKey(ctx, req.(*SignTransactionBySecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Adapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastBlockHeight",
			Handler:    _Adapter_GetLastBlockHeight_Handler,
		},
		{
			MethodName: "GenerateAddress",
			Handler:    _Adapter_GenerateAddress_Handler,
		},
		{
			MethodName: "ValidateAddress",
			Handler:    _Adapter_ValidateAddress_Handler,
		},
		{
			MethodName: "Fee",
			Handler:    _Adapter_Fee_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Adapter_GetBalance_Handler,
		},
		{
			MethodName: "GetAllBalances",
			Handler:    _Adapter_GetAllBalances_Handler,
		},
		{
			MethodName: "GetRawTransactionBySendersAddress",
			Handler:    _Adapter_GetRawTransactionBySendersAddress_Handler,
		},
		{
			MethodName: "GetRawTransactionBySendersPublicKey",
			Handler:    _Adapter_GetRawTransactionBySendersPublicKey_Handler,
		},
		{
			MethodName: "SignTransaction",
			Handler:    _Adapter_SignTransaction_Handler,
		},
		{
			MethodName: "SignTransactionBySecretKey",
			Handler:    _Adapter_SignTransactionBySecretKey_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Adapter_SendTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _Adapter_GetTransactionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "waves_adapter.proto",
}
