node:
  host: https://nodes.wavesplatform.com
  startBlock: 1432700
  confirmations: 6
  chain: WAVES
  apiKey:

db:
  name: block_db
  host: localhost:27017
port: 5004
callbackUrl: localhost:5020

#config for vostok
#node:
#  host: http://54.76.145.18:6862
#  startBlock: 1432700
#  confirmations: 6
#  chain: VOSTOK
#  apiKey: 8qNHJZPOtQ