// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ergo_adapter.proto

package blockchain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message for getting information by account address
type AddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressRequest) Reset()         { *m = AddressRequest{} }
func (m *AddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()    {}
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{0}
}

func (m *AddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressRequest.Unmarshal(m, b)
}
func (m *AddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressRequest.Marshal(b, m, deterministic)
}
func (m *AddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressRequest.Merge(m, src)
}
func (m *AddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddressRequest.Size(m)
}
func (m *AddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressRequest proto.InternalMessageInfo

func (m *AddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// fee request message
type FeeRequest struct {
	SendersPublicKey     string   `protobuf:"bytes,1,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeRequest) Reset()         { *m = FeeRequest{} }
func (m *FeeRequest) String() string { return proto.CompactTextString(m) }
func (*FeeRequest) ProtoMessage()    {}
func (*FeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{1}
}

func (m *FeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeRequest.Unmarshal(m, b)
}
func (m *FeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeRequest.Marshal(b, m, deterministic)
}
func (m *FeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRequest.Merge(m, src)
}
func (m *FeeRequest) XXX_Size() int {
	return xxx_messageInfo_FeeRequest.Size(m)
}
func (m *FeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRequest proto.InternalMessageInfo

func (m *FeeRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *FeeRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// The response message containing transaction's fee
type FeeReply struct {
	Fee                  string   `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeReply) Reset()         { *m = FeeReply{} }
func (m *FeeReply) String() string { return proto.CompactTextString(m) }
func (*FeeReply) ProtoMessage()    {}
func (*FeeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{2}
}

func (m *FeeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeReply.Unmarshal(m, b)
}
func (m *FeeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeReply.Marshal(b, m, deterministic)
}
func (m *FeeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeReply.Merge(m, src)
}
func (m *FeeReply) XXX_Size() int {
	return xxx_messageInfo_FeeReply.Size(m)
}
func (m *FeeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeReply.DiscardUnknown(m)
}

var xxx_messageInfo_FeeReply proto.InternalMessageInfo

func (m *FeeReply) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

// The response message containing account's balance with assets balances
type GetAllBalancesReply struct {
	Amount               string                              `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetBalances        []*GetAllBalancesReply_AssetBalance `protobuf:"bytes,2,rep,name=assetBalances,proto3" json:"assetBalances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetAllBalancesReply) Reset()         { *m = GetAllBalancesReply{} }
func (m *GetAllBalancesReply) String() string { return proto.CompactTextString(m) }
func (*GetAllBalancesReply) ProtoMessage()    {}
func (*GetAllBalancesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{3}
}

func (m *GetAllBalancesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalancesReply.Unmarshal(m, b)
}
func (m *GetAllBalancesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalancesReply.Marshal(b, m, deterministic)
}
func (m *GetAllBalancesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalancesReply.Merge(m, src)
}
func (m *GetAllBalancesReply) XXX_Size() int {
	return xxx_messageInfo_GetAllBalancesReply.Size(m)
}
func (m *GetAllBalancesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalancesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalancesReply proto.InternalMessageInfo

func (m *GetAllBalancesReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetAllBalancesReply) GetAssetBalances() []*GetAllBalancesReply_AssetBalance {
	if m != nil {
		return m.AssetBalances
	}
	return nil
}

type GetAllBalancesReply_AssetBalance struct {
	AssetId              string   `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBalancesReply_AssetBalance) Reset()         { *m = GetAllBalancesReply_AssetBalance{} }
func (m *GetAllBalancesReply_AssetBalance) String() string { return proto.CompactTextString(m) }
func (*GetAllBalancesReply_AssetBalance) ProtoMessage()    {}
func (*GetAllBalancesReply_AssetBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{3, 0}
}

func (m *GetAllBalancesReply_AssetBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Unmarshal(m, b)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Marshal(b, m, deterministic)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBalancesReply_AssetBalance.Merge(m, src)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_Size() int {
	return xxx_messageInfo_GetAllBalancesReply_AssetBalance.Size(m)
}
func (m *GetAllBalancesReply_AssetBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBalancesReply_AssetBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBalancesReply_AssetBalance proto.InternalMessageInfo

func (m *GetAllBalancesReply_AssetBalance) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *GetAllBalancesReply_AssetBalance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The response message containing result of address's validation
type ValidateAddressReply struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressReply) Reset()         { *m = ValidateAddressReply{} }
func (m *ValidateAddressReply) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressReply) ProtoMessage()    {}
func (*ValidateAddressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{4}
}

func (m *ValidateAddressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressReply.Unmarshal(m, b)
}
func (m *ValidateAddressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressReply.Marshal(b, m, deterministic)
}
func (m *ValidateAddressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressReply.Merge(m, src)
}
func (m *ValidateAddressReply) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressReply.Size(m)
}
func (m *ValidateAddressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressReply proto.InternalMessageInfo

func (m *ValidateAddressReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// The request message for raw transaction creation
type RawTransactionRequest struct {
	AddressFrom          string   `protobuf:"bytes,1,opt,name=addressFrom,proto3" json:"addressFrom,omitempty"`
	SendersPublicKey     string   `protobuf:"bytes,2,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AddressTo            string   `protobuf:"bytes,3,opt,name=addressTo,proto3" json:"addressTo,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId              string   `protobuf:"bytes,5,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionRequest) Reset()         { *m = RawTransactionRequest{} }
func (m *RawTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*RawTransactionRequest) ProtoMessage()    {}
func (*RawTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{5}
}

func (m *RawTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionRequest.Unmarshal(m, b)
}
func (m *RawTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionRequest.Marshal(b, m, deterministic)
}
func (m *RawTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionRequest.Merge(m, src)
}
func (m *RawTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_RawTransactionRequest.Size(m)
}
func (m *RawTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionRequest proto.InternalMessageInfo

func (m *RawTransactionRequest) GetAddressFrom() string {
	if m != nil {
		return m.AddressFrom
	}
	return ""
}

func (m *RawTransactionRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *RawTransactionRequest) GetAddressTo() string {
	if m != nil {
		return m.AddressTo
	}
	return ""
}

func (m *RawTransactionRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RawTransactionRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// The request message for raw transaction with many recipients creation
type RawMassTransactionRequest struct {
	AddressFrom          string                           `protobuf:"bytes,1,opt,name=addressFrom,proto3" json:"addressFrom,omitempty"`
	SendersPublicKey     string                           `protobuf:"bytes,2,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	AssetId              string                           `protobuf:"bytes,5,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Outs                 []*RawMassTransactionRequest_Out `protobuf:"bytes,6,rep,name=outs,proto3" json:"outs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *RawMassTransactionRequest) Reset()         { *m = RawMassTransactionRequest{} }
func (m *RawMassTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*RawMassTransactionRequest) ProtoMessage()    {}
func (*RawMassTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{6}
}

func (m *RawMassTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMassTransactionRequest.Unmarshal(m, b)
}
func (m *RawMassTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMassTransactionRequest.Marshal(b, m, deterministic)
}
func (m *RawMassTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMassTransactionRequest.Merge(m, src)
}
func (m *RawMassTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_RawMassTransactionRequest.Size(m)
}
func (m *RawMassTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMassTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawMassTransactionRequest proto.InternalMessageInfo

func (m *RawMassTransactionRequest) GetAddressFrom() string {
	if m != nil {
		return m.AddressFrom
	}
	return ""
}

func (m *RawMassTransactionRequest) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *RawMassTransactionRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *RawMassTransactionRequest) GetOuts() []*RawMassTransactionRequest_Out {
	if m != nil {
		return m.Outs
	}
	return nil
}

type RawMassTransactionRequest_Out struct {
	AddressTo            string   `protobuf:"bytes,1,opt,name=addressTo,proto3" json:"addressTo,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawMassTransactionRequest_Out) Reset()         { *m = RawMassTransactionRequest_Out{} }
func (m *RawMassTransactionRequest_Out) String() string { return proto.CompactTextString(m) }
func (*RawMassTransactionRequest_Out) ProtoMessage()    {}
func (*RawMassTransactionRequest_Out) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{6, 0}
}

func (m *RawMassTransactionRequest_Out) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMassTransactionRequest_Out.Unmarshal(m, b)
}
func (m *RawMassTransactionRequest_Out) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMassTransactionRequest_Out.Marshal(b, m, deterministic)
}
func (m *RawMassTransactionRequest_Out) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMassTransactionRequest_Out.Merge(m, src)
}
func (m *RawMassTransactionRequest_Out) XXX_Size() int {
	return xxx_messageInfo_RawMassTransactionRequest_Out.Size(m)
}
func (m *RawMassTransactionRequest_Out) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMassTransactionRequest_Out.DiscardUnknown(m)
}

var xxx_messageInfo_RawMassTransactionRequest_Out proto.InternalMessageInfo

func (m *RawMassTransactionRequest_Out) GetAddressTo() string {
	if m != nil {
		return m.AddressTo
	}
	return ""
}

func (m *RawMassTransactionRequest_Out) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// The response message containing raw transaction
type RawTransactionReply struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionReply) Reset()         { *m = RawTransactionReply{} }
func (m *RawTransactionReply) String() string { return proto.CompactTextString(m) }
func (*RawTransactionReply) ProtoMessage()    {}
func (*RawTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{7}
}

func (m *RawTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionReply.Unmarshal(m, b)
}
func (m *RawTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionReply.Marshal(b, m, deterministic)
}
func (m *RawTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionReply.Merge(m, src)
}
func (m *RawTransactionReply) XXX_Size() int {
	return xxx_messageInfo_RawTransactionReply.Size(m)
}
func (m *RawTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionReply proto.InternalMessageInfo

func (m *RawTransactionReply) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The request message for singing transaction
type SendTransactionRequest struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{8}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// The response message containing transaction's id
type SendTransactionReply struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionReply) Reset()         { *m = SendTransactionReply{} }
func (m *SendTransactionReply) String() string { return proto.CompactTextString(m) }
func (*SendTransactionReply) ProtoMessage()    {}
func (*SendTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{9}
}

func (m *SendTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionReply.Unmarshal(m, b)
}
func (m *SendTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionReply.Marshal(b, m, deterministic)
}
func (m *SendTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionReply.Merge(m, src)
}
func (m *SendTransactionReply) XXX_Size() int {
	return xxx_messageInfo_SendTransactionReply.Size(m)
}
func (m *SendTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionReply proto.InternalMessageInfo

func (m *SendTransactionReply) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// The request message for getting transaction by hash
type TransactionByHashRequest struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionByHashRequest) Reset()         { *m = TransactionByHashRequest{} }
func (m *TransactionByHashRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionByHashRequest) ProtoMessage()    {}
func (*TransactionByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{10}
}

func (m *TransactionByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionByHashRequest.Unmarshal(m, b)
}
func (m *TransactionByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionByHashRequest.Marshal(b, m, deterministic)
}
func (m *TransactionByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionByHashRequest.Merge(m, src)
}
func (m *TransactionByHashRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionByHashRequest.Size(m)
}
func (m *TransactionByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionByHashRequest proto.InternalMessageInfo

func (m *TransactionByHashRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// The response message for getting transaction by hash
type TransactionByHashReply struct {
	SenderAddress        string         `protobuf:"bytes,1,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	SendersPublicKey     string         `protobuf:"bytes,2,opt,name=sendersPublicKey,proto3" json:"sendersPublicKey,omitempty"`
	RecipientAddress     string         `protobuf:"bytes,3,opt,name=recipientAddress,proto3" json:"recipientAddress,omitempty"`
	Amount               string         `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId              string         `protobuf:"bytes,5,opt,name=assetId,proto3" json:"assetId,omitempty"`
	TxHash               string         `protobuf:"bytes,6,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Fee                  string         `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Data                 string         `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Status               string         `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Inputs               []*InputOutput `protobuf:"bytes,10,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*InputOutput `protobuf:"bytes,11,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionByHashReply) Reset()         { *m = TransactionByHashReply{} }
func (m *TransactionByHashReply) String() string { return proto.CompactTextString(m) }
func (*TransactionByHashReply) ProtoMessage()    {}
func (*TransactionByHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{11}
}

func (m *TransactionByHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionByHashReply.Unmarshal(m, b)
}
func (m *TransactionByHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionByHashReply.Marshal(b, m, deterministic)
}
func (m *TransactionByHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionByHashReply.Merge(m, src)
}
func (m *TransactionByHashReply) XXX_Size() int {
	return xxx_messageInfo_TransactionByHashReply.Size(m)
}
func (m *TransactionByHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionByHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionByHashReply proto.InternalMessageInfo

func (m *TransactionByHashReply) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *TransactionByHashReply) GetSendersPublicKey() string {
	if m != nil {
		return m.SendersPublicKey
	}
	return ""
}

func (m *TransactionByHashReply) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *TransactionByHashReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionByHashReply) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *TransactionByHashReply) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TransactionByHashReply) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *TransactionByHashReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TransactionByHashReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionByHashReply) GetInputs() []*InputOutput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TransactionByHashReply) GetOutputs() []*InputOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type InputOutput struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputOutput) Reset()         { *m = InputOutput{} }
func (m *InputOutput) String() string { return proto.CompactTextString(m) }
func (*InputOutput) ProtoMessage()    {}
func (*InputOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_9606996f3f4b5710, []int{12}
}

func (m *InputOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputOutput.Unmarshal(m, b)
}
func (m *InputOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputOutput.Marshal(b, m, deterministic)
}
func (m *InputOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputOutput.Merge(m, src)
}
func (m *InputOutput) XXX_Size() int {
	return xxx_messageInfo_InputOutput.Size(m)
}
func (m *InputOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_InputOutput.DiscardUnknown(m)
}

var xxx_messageInfo_InputOutput proto.InternalMessageInfo

func (m *InputOutput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InputOutput) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressRequest)(nil), "blockchain.AddressRequest")
	proto.RegisterType((*FeeRequest)(nil), "blockchain.FeeRequest")
	proto.RegisterType((*FeeReply)(nil), "blockchain.FeeReply")
	proto.RegisterType((*GetAllBalancesReply)(nil), "blockchain.GetAllBalancesReply")
	proto.RegisterType((*GetAllBalancesReply_AssetBalance)(nil), "blockchain.GetAllBalancesReply.AssetBalance")
	proto.RegisterType((*ValidateAddressReply)(nil), "blockchain.ValidateAddressReply")
	proto.RegisterType((*RawTransactionRequest)(nil), "blockchain.RawTransactionRequest")
	proto.RegisterType((*RawMassTransactionRequest)(nil), "blockchain.RawMassTransactionRequest")
	proto.RegisterType((*RawMassTransactionRequest_Out)(nil), "blockchain.RawMassTransactionRequest.Out")
	proto.RegisterType((*RawTransactionReply)(nil), "blockchain.RawTransactionReply")
	proto.RegisterType((*SendTransactionRequest)(nil), "blockchain.SendTransactionRequest")
	proto.RegisterType((*SendTransactionReply)(nil), "blockchain.SendTransactionReply")
	proto.RegisterType((*TransactionByHashRequest)(nil), "blockchain.TransactionByHashRequest")
	proto.RegisterType((*TransactionByHashReply)(nil), "blockchain.TransactionByHashReply")
	proto.RegisterType((*InputOutput)(nil), "blockchain.InputOutput")
}

func init() { proto.RegisterFile("ergo_adapter.proto", fileDescriptor_9606996f3f4b5710) }

var fileDescriptor_9606996f3f4b5710 = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdb, 0x6e, 0xd3, 0x30,
	0x18, 0x6e, 0xda, 0xae, 0xdd, 0xfe, 0xee, 0xe8, 0x75, 0x25, 0x54, 0x93, 0x28, 0xd6, 0x26, 0x8d,
	0x6a, 0x2a, 0x62, 0x88, 0x2b, 0x84, 0xa0, 0xbb, 0xd8, 0x98, 0x10, 0x2a, 0x84, 0x09, 0x69, 0x57,
	0x93, 0xd7, 0x18, 0x16, 0x91, 0x25, 0x25, 0x76, 0x58, 0x77, 0xcb, 0x3b, 0xf1, 0x04, 0xbc, 0x07,
	0xaf, 0x02, 0xb2, 0x9d, 0xac, 0x76, 0x0e, 0x3b, 0x5c, 0x70, 0x17, 0xff, 0xfe, 0xfe, 0xcf, 0xff,
	0xf1, 0x6b, 0x01, 0xd1, 0xe8, 0x6b, 0x78, 0x4a, 0x5c, 0x32, 0xe1, 0x34, 0x1a, 0x4c, 0xa2, 0x90,
	0x87, 0x08, 0xce, 0xfc, 0x70, 0xfc, 0x6d, 0x7c, 0x4e, 0xbc, 0x00, 0xf7, 0x61, 0x79, 0xe8, 0xba,
	0x11, 0x65, 0xcc, 0xa1, 0xdf, 0x63, 0xca, 0x38, 0xb2, 0xa1, 0x49, 0x94, 0xc5, 0xb6, 0x7a, 0xd6,
	0xce, 0x82, 0x93, 0x1e, 0xb1, 0x03, 0x70, 0x40, 0x69, 0x8a, 0xeb, 0xc3, 0x2a, 0xa3, 0x81, 0x4b,
	0x23, 0xf6, 0x21, 0x3e, 0xf3, 0xbd, 0xf1, 0x3b, 0x7a, 0x95, 0x38, 0xe4, 0xec, 0x92, 0x93, 0x31,
	0xca, 0x8f, 0x5c, 0xbb, 0x9a, 0x70, 0xaa, 0x23, 0xde, 0x84, 0x79, 0xc9, 0x39, 0xf1, 0xaf, 0xd0,
	0x2a, 0xd4, 0xbe, 0x50, 0x9a, 0x90, 0x88, 0x4f, 0xfc, 0xdb, 0x82, 0xf5, 0x43, 0xca, 0x87, 0xbe,
	0xbf, 0x4f, 0x7c, 0x12, 0x8c, 0x29, 0x53, 0xc8, 0x0e, 0x34, 0xc8, 0x45, 0x18, 0x07, 0x3c, 0x01,
	0x27, 0x27, 0xe4, 0xc0, 0x92, 0x24, 0x4e, 0xd1, 0x76, 0xb5, 0x57, 0xdb, 0x69, 0xed, 0xed, 0x0e,
	0x66, 0x19, 0x0f, 0x0a, 0xf8, 0x06, 0x43, 0xcd, 0xc9, 0x31, 0x29, 0xba, 0x6f, 0x60, 0x51, 0xbf,
	0xd6, 0x73, 0xb1, 0x8c, 0x5c, 0xb4, 0xa8, 0xaa, 0x7a, 0x54, 0x78, 0x17, 0xda, 0x9f, 0x89, 0xef,
	0xb9, 0x84, 0xd3, 0xeb, 0x5a, 0x8b, 0x2c, 0xda, 0x30, 0xf7, 0x43, 0xd8, 0x25, 0xcf, 0xbc, 0xa3,
	0x0e, 0xf8, 0x97, 0x05, 0x1b, 0x0e, 0xb9, 0x3c, 0x8e, 0x48, 0xc0, 0xc8, 0x98, 0x7b, 0x61, 0x90,
	0x56, 0xbc, 0x07, 0xad, 0xa4, 0x15, 0x07, 0x51, 0x78, 0x91, 0xbc, 0xae, 0x9b, 0x0a, 0x7b, 0x52,
	0x2d, 0xe9, 0xc9, 0x26, 0x2c, 0x24, 0xae, 0xc7, 0xa1, 0x5d, 0x93, 0xa0, 0x99, 0x41, 0xcb, 0xa5,
	0x6e, 0x54, 0x58, 0xcb, 0x7e, 0xce, 0xec, 0xe4, 0x5f, 0x0b, 0x1e, 0x3a, 0xe4, 0xf2, 0x3d, 0x61,
	0xec, 0xbf, 0xc7, 0x5e, 0x1a, 0x05, 0x7a, 0x05, 0xf5, 0x30, 0xe6, 0xcc, 0x6e, 0xc8, 0xc6, 0x3f,
	0xd1, 0x1b, 0x5f, 0x1a, 0xdc, 0x60, 0x14, 0x73, 0x47, 0xba, 0x75, 0x5f, 0x42, 0x6d, 0x14, 0x73,
	0xb3, 0x36, 0x56, 0x79, 0x6d, 0xcc, 0x3e, 0x6f, 0xc3, 0x7a, 0xb6, 0x71, 0xa2, 0xcd, 0xcb, 0x50,
	0xe5, 0x53, 0xc9, 0xb2, 0xe8, 0x54, 0xf9, 0x14, 0xef, 0x40, 0xe7, 0x13, 0x0d, 0xdc, 0x82, 0x22,
	0x65, 0x91, 0x7d, 0x68, 0xe7, 0x90, 0x82, 0x11, 0x41, 0x9d, 0x4f, 0xaf, 0xe7, 0x4f, 0x7e, 0xe3,
	0x3d, 0xb0, 0x35, 0xdc, 0xfe, 0xd5, 0x5b, 0xc2, 0xce, 0x53, 0xde, 0x0e, 0x34, 0xf8, 0x54, 0x18,
	0xd2, 0x75, 0x51, 0x27, 0xfc, 0xb3, 0x06, 0x9d, 0x02, 0x27, 0xf1, 0xc4, 0x16, 0x2c, 0xa9, 0xaa,
	0x0f, 0x0d, 0x2d, 0x30, 0x8d, 0xf7, 0xea, 0x59, 0x1f, 0x56, 0x23, 0x3a, 0xf6, 0x26, 0x1e, 0x0d,
	0x78, 0x4a, 0xaa, 0xc6, 0x2e, 0x67, 0xbf, 0xff, 0xf4, 0x69, 0x29, 0x36, 0xf4, 0x14, 0x53, 0x4d,
	0x69, 0x5e, 0x6b, 0x8a, 0x28, 0x9e, 0x4b, 0x38, 0xb1, 0xe7, 0x55, 0xf1, 0xc4, 0xb7, 0xf0, 0x66,
	0x9c, 0xf0, 0x98, 0xd9, 0x0b, 0xca, 0x5b, 0x9d, 0xd0, 0x53, 0x68, 0x78, 0xc1, 0x44, 0xcc, 0x13,
	0xc8, 0x79, 0x7a, 0xa0, 0xcf, 0xd3, 0x91, 0xb8, 0x19, 0xc5, 0x7c, 0x12, 0x73, 0x27, 0x81, 0xa1,
	0x67, 0xd0, 0x0c, 0xa5, 0x85, 0xd9, 0xad, 0x9b, 0x3d, 0x52, 0x1c, 0x7e, 0x0d, 0x2d, 0xcd, 0x5e,
	0x2e, 0xbf, 0x65, 0x63, 0xb7, 0xf7, 0xa7, 0x0e, 0xcd, 0xa1, 0x12, 0x78, 0xf4, 0x11, 0x56, 0x32,
	0x52, 0x83, 0xba, 0x7a, 0x04, 0xa6, 0xd6, 0x77, 0x7b, 0xfa, 0x5d, 0x91, 0x46, 0xe1, 0x0a, 0x7a,
	0x01, 0xb5, 0x03, 0x4a, 0x51, 0x47, 0x87, 0xce, 0x7e, 0x06, 0xba, 0xed, 0x9c, 0x5d, 0xb9, 0x8d,
	0x60, 0xd9, 0x54, 0xda, 0x1b, 0x03, 0x79, 0x74, 0x8b, 0x42, 0xe3, 0x0a, 0x3a, 0x81, 0xb5, 0x43,
	0xca, 0xcd, 0x05, 0x43, 0x8f, 0x33, 0x0b, 0x9e, 0x5f, 0x2a, 0x93, 0xba, 0x60, 0x3f, 0x71, 0x05,
	0x11, 0xd8, 0x50, 0xd4, 0x19, 0x7d, 0x40, 0xdb, 0x77, 0xd2, 0x8f, 0xbb, 0x3c, 0x71, 0x02, 0x2b,
	0x99, 0x55, 0x46, 0x58, 0xf7, 0x2a, 0x56, 0x04, 0xb3, 0x41, 0x45, 0x5a, 0x80, 0x2b, 0xe8, 0x14,
	0xd6, 0x72, 0x4b, 0x8c, 0xb6, 0x74, 0xc7, 0x32, 0x61, 0xe8, 0xe2, 0x5b, 0x50, 0xf2, 0x81, 0xb3,
	0x86, 0xfc, 0xdb, 0xf0, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x95, 0x30, 0x0b, 0x4c,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdapterClient interface {
	// Validate address
	ValidateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error)
	// Get transaction's fee
	Fee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeReply, error)
	// Get account's balance with assets balances
	GetAllBalances(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetAllBalancesReply, error)
	// request to create raw transaction
	GetRawTransaction(ctx context.Context, in *RawTransactionRequest, opts ...grpc.CallOption) (*RawTransactionReply, error)
	// request to create raw transaction with many recipients
	GetRawMassTransaction(ctx context.Context, in *RawMassTransactionRequest, opts ...grpc.CallOption) (*RawTransactionReply, error)
	// Send transaction
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error)
	// Get transaction
	TransactionByHash(ctx context.Context, in *TransactionByHashRequest, opts ...grpc.CallOption) (*TransactionByHashReply, error)
}

type adapterClient struct {
	cc *grpc.ClientConn
}

func NewAdapterClient(cc *grpc.ClientConn) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) ValidateAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*ValidateAddressReply, error) {
	out := new(ValidateAddressReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/ValidateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Fee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeReply, error) {
	out := new(FeeReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/Fee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetAllBalances(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*GetAllBalancesReply, error) {
	out := new(GetAllBalancesReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetAllBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetRawTransaction(ctx context.Context, in *RawTransactionRequest, opts ...grpc.CallOption) (*RawTransactionReply, error) {
	out := new(RawTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetRawMassTransaction(ctx context.Context, in *RawMassTransactionRequest, opts ...grpc.CallOption) (*RawTransactionReply, error) {
	out := new(RawTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/GetRawMassTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error) {
	out := new(SendTransactionReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) TransactionByHash(ctx context.Context, in *TransactionByHashRequest, opts ...grpc.CallOption) (*TransactionByHashReply, error) {
	out := new(TransactionByHashReply)
	err := c.cc.Invoke(ctx, "/blockchain.Adapter/TransactionByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServer is the server API for Adapter service.
type AdapterServer interface {
	// Validate address
	ValidateAddress(context.Context, *AddressRequest) (*ValidateAddressReply, error)
	// Get transaction's fee
	Fee(context.Context, *FeeRequest) (*FeeReply, error)
	// Get account's balance with assets balances
	GetAllBalances(context.Context, *AddressRequest) (*GetAllBalancesReply, error)
	// request to create raw transaction
	GetRawTransaction(context.Context, *RawTransactionRequest) (*RawTransactionReply, error)
	// request to create raw transaction with many recipients
	GetRawMassTransaction(context.Context, *RawMassTransactionRequest) (*RawTransactionReply, error)
	// Send transaction
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionReply, error)
	// Get transaction
	TransactionByHash(context.Context, *TransactionByHashRequest) (*TransactionByHashReply, error)
}

func RegisterAdapterServer(s *grpc.Server, srv AdapterServer) {
	s.RegisterService(&_Adapter_serviceDesc, srv)
}

func _Adapter_ValidateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ValidateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/ValidateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ValidateAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Fee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Fee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/Fee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Fee(ctx, req.(*FeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetAllBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetAllBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetAllBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetAllBalances(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetRawTransaction(ctx, req.(*RawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetRawMassTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMassTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetRawMassTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/GetRawMassTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetRawMassTransaction(ctx, req.(*RawMassTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_TransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).TransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Adapter/TransactionByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).TransactionByHash(ctx, req.(*TransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Adapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAddress",
			Handler:    _Adapter_ValidateAddress_Handler,
		},
		{
			MethodName: "Fee",
			Handler:    _Adapter_Fee_Handler,
		},
		{
			MethodName: "GetAllBalances",
			Handler:    _Adapter_GetAllBalances_Handler,
		},
		{
			MethodName: "GetRawTransaction",
			Handler:    _Adapter_GetRawTransaction_Handler,
		},
		{
			MethodName: "GetRawMassTransaction",
			Handler:    _Adapter_GetRawMassTransaction_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Adapter_SendTransaction_Handler,
		},
		{
			MethodName: "TransactionByHash",
			Handler:    _Adapter_TransactionByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ergo_adapter.proto",
}
