node:
  host: localhost:18332
  user: user
  password: pass
  httppostmode: true
  disabletls: true
  chaintype: mainnet
db:
  name: block_db
  host: localhost:27017
dataservice:
  url: https://insight.bitpay.com/api
decimals: 8
port: 5007
